import type { TaskTemplate } from "./types";

type RawBleepPackItem = Omit<TaskTemplate, "encounterId"> & {
  encounterId?: string | null;
};

const encounterMap: Record<string, string | undefined> = {
  ed_hypotensive_sepsis: "occult_sepsis_adrenal_crisis",
  resp_acute_hypercapnia: "hypercapnic_drowsiness_oxygen",
  cardiology_wide_complex_tachy: "broad_complex_tachy",
  elderly_stroke_thrombolysis_window: "stroke_mimic",
  surgical_upper_gi_bleed: "ugi_bleed",
  mau_dka_new_diagnosis: "dka",
  pharmacy_potassium_critical: "aki_hyperkalaemia",
  radiology_ctpa_massive_pe: "pe_shock_pregnancy_postpartum",
  mau_mild_chest_pain_trop_rise: "nstemi",
  resp_small_oxygen_increase: "hypercapnic_drowsiness_oxygen",
  mau_low_sodium_drowsy: "hyponatraemia_seizure_desmopressin",
  ed_quiet_abdominal_pain: "occult_sepsis_adrenal_crisis",
  elderly_wandering_anticoagulated: "stroke_mimic",
};

const rawBleepPack: RawBleepPackItem[] = [
  {
    id: "ed_hypotensive_sepsis",
    locationId: "ed_resus",
    message: "ED asking if you can review ?sepsis, BP 82 systolic after fluids",
    sender: "ED SHO",
    source: "pager",
    claimedUrgency: "urgent review when free",
    trueUrgency: "critical",
    category: "emergency",
    encounterId: "ed_hypotensive_sepsis",
    timeToDeterioration: 10,
    vague: false,
    regSense: false,
    weight: 12,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -5,
      reputation: -2,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -8,
    },
    handledWell: {
      patientSafety: 5,
      reputation: 2,
      focus: -1,
      stamina: -2,
      clinicalConfidence: 3,
      handoverQuality: 1,
      chaosSurvived: 2,
      score: 8,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2"],
    delegationDuration: {},
  },
  {
    id: "resp_acute_hypercapnia",
    locationId: "respiratory",
    message: "Ward asking about drowsy COPD patient, gas just back",
    sender: "Respiratory nurse",
    source: "pager",
    claimedUrgency: "can you advise NIV plan",
    trueUrgency: "critical",
    category: "emergency",
    encounterId: "resp_acute_hypercapnia",
    timeToDeterioration: 15,
    vague: true,
    regSense: false,
    weight: 11,
    phases: ["early", "deep", "pre_handover"],
    ignored: {
      patientSafety: -5,
      reputation: -2,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -8,
    },
    handledWell: {
      patientSafety: 5,
      reputation: 2,
      focus: -1,
      stamina: -2,
      clinicalConfidence: 3,
      handoverQuality: 1,
      chaosSurvived: 2,
      score: 8,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "locum_no_login"],
    delegationDuration: {},
  },
  {
    id: "cardiology_wide_complex_tachy",
    locationId: "cardiology",
    message:
      "Patient on CCU monitor in broad complex tachycardia, nurse wants review",
    sender: "CCU nurse",
    source: "pager",
    claimedUrgency: "urgent",
    trueUrgency: "critical",
    category: "emergency",
    encounterId: "cardiology_wide_complex_tachy",
    timeToDeterioration: 10,
    vague: false,
    regSense: false,
    weight: 12,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -5,
      reputation: -3,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -9,
    },
    handledWell: {
      patientSafety: 5,
      reputation: 3,
      focus: -1,
      stamina: -2,
      clinicalConfidence: 3,
      handoverQuality: 1,
      chaosSurvived: 2,
      score: 9,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2"],
    delegationDuration: {},
  },
  {
    id: "mau_anaphylaxis_antibiotic",
    locationId: "mau",
    message:
      "New rash and wheeze after IV antibiotic, nurse asking if chlorphenamine enough",
    sender: "MAU nurse",
    source: "pager",
    claimedUrgency: "quick advice",
    trueUrgency: "critical",
    category: "emergency",
    encounterId: "mau_anaphylaxis_antibiotic",
    timeToDeterioration: 10,
    vague: false,
    regSense: false,
    weight: 12,
    phases: ["early", "deep", "pre_handover"],
    ignored: {
      patientSafety: -5,
      reputation: -2,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -8,
    },
    handledWell: {
      patientSafety: 5,
      reputation: 2,
      focus: -1,
      stamina: -1,
      clinicalConfidence: 3,
      handoverQuality: 1,
      chaosSurvived: 2,
      score: 8,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2"],
    delegationDuration: {},
  },
  {
    id: "elderly_stroke_thrombolysis_window",
    locationId: "elderly",
    message: "New facial droop noticed on bay, last seen well maybe midnight",
    sender: "Ward nurse",
    source: "pager",
    claimedUrgency: "doctor review please",
    trueUrgency: "high",
    category: "urgent",
    encounterId: "elderly_stroke_thrombolysis_window",
    timeToDeterioration: 25,
    vague: true,
    regSense: false,
    weight: 10,
    phases: ["deep", "pre_handover"],
    ignored: {
      patientSafety: -4,
      reputation: -2,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -7,
    },
    handledWell: {
      patientSafety: 4,
      reputation: 2,
      focus: -1,
      stamina: -1,
      clinicalConfidence: 2,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 7,
    },
    delegableTo: ["trusted_fy2"],
    riskyDelegateTo: ["fy1", "locum_no_login"],
    delegationDuration: { trusted_fy2: 8 },
  },
  {
    id: "surgical_upper_gi_bleed",
    locationId: "surgical",
    message:
      "Surgical outlier vomiting coffee grounds, Hb dropped since evening",
    sender: "Surgical ward nurse",
    source: "pager",
    claimedUrgency: "medical review requested",
    trueUrgency: "high",
    category: "urgent",
    encounterId: "surgical_upper_gi_bleed",
    timeToDeterioration: 20,
    vague: false,
    regSense: false,
    weight: 10,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -4,
      reputation: -2,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -7,
    },
    handledWell: {
      patientSafety: 4,
      reputation: 2,
      focus: -1,
      stamina: -2,
      clinicalConfidence: 2,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 7,
    },
    delegableTo: ["trusted_fy2"],
    riskyDelegateTo: ["fy1", "locum_no_login"],
    delegationDuration: { trusted_fy2: 10 },
  },
  {
    id: "mau_dka_new_diagnosis",
    locationId: "mau",
    message: "Ketones 6.2 on new diabetic admission, nurse asking for fluids",
    sender: "MAU nurse",
    source: "pager",
    claimedUrgency: "urgent prescription",
    trueUrgency: "high",
    category: "urgent",
    encounterId: "mau_dka_new_diagnosis",
    timeToDeterioration: 30,
    vague: false,
    regSense: false,
    weight: 10,
    phases: ["early", "deep", "pre_handover"],
    ignored: {
      patientSafety: -4,
      reputation: -2,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -7,
    },
    handledWell: {
      patientSafety: 4,
      reputation: 2,
      focus: -1,
      stamina: -2,
      clinicalConfidence: 2,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 7,
    },
    delegableTo: ["trusted_fy2"],
    riskyDelegateTo: ["fy1", "locum_no_login"],
    delegationDuration: { trusted_fy2: 12 },
  },
  {
    id: "icu_unexpected_stepdown_decline",
    locationId: "icu",
    message: "ICU outreach asking you to see recent stepdown, NEWS now 9",
    sender: "ICU outreach nurse",
    source: "pager",
    claimedUrgency: "joint review",
    trueUrgency: "high",
    category: "urgent",
    encounterId: "icu_unexpected_stepdown_decline",
    timeToDeterioration: 20,
    vague: false,
    regSense: false,
    weight: 10,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -4,
      reputation: -2,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -7,
    },
    handledWell: {
      patientSafety: 4,
      reputation: 2,
      focus: -1,
      stamina: -2,
      clinicalConfidence: 2,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 7,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login"],
    delegationDuration: {},
  },
  {
    id: "pharmacy_potassium_critical",
    locationId: "pharmacy",
    message: "Lab phoned K 6.9, sample not haemolysed, patient on renal ward",
    sender: "On-call pharmacist",
    source: "pager",
    claimedUrgency: "please action tonight",
    trueUrgency: "high",
    category: "urgent",
    encounterId: "pharmacy_potassium_critical",
    timeToDeterioration: 25,
    vague: false,
    regSense: false,
    weight: 10,
    phases: ["early", "deep", "pre_handover"],
    ignored: {
      patientSafety: -4,
      reputation: -2,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -7,
    },
    handledWell: {
      patientSafety: 4,
      reputation: 2,
      focus: -1,
      stamina: -1,
      clinicalConfidence: 2,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 7,
    },
    delegableTo: ["trusted_fy2"],
    riskyDelegateTo: ["fy1", "locum_no_login"],
    delegationDuration: { trusted_fy2: 8 },
  },
  {
    id: "radiology_ctpa_massive_pe",
    locationId: "radiology",
    message:
      "Radiology asking who is taking responsibility for large saddle PE report",
    sender: "Radiology registrar",
    source: "pager",
    claimedUrgency: "please clarify team",
    trueUrgency: "critical",
    category: "emergency",
    encounterId: "radiology_ctpa_massive_pe",
    timeToDeterioration: 15,
    vague: true,
    regSense: false,
    weight: 11,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -5,
      reputation: -2,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -8,
    },
    handledWell: {
      patientSafety: 5,
      reputation: 2,
      focus: -1,
      stamina: -2,
      clinicalConfidence: 3,
      handoverQuality: 1,
      chaosSurvived: 2,
      score: 8,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login"],
    delegationDuration: {},
  },
  {
    id: "mau_mild_chest_pain_trop_rise",
    locationId: "mau",
    message: "Chest pain settled, repeat trop has gone up a bit",
    sender: "MAU FY1",
    source: "pager",
    claimedUrgency: "routine senior advice",
    trueUrgency: "high",
    category: "ambiguous",
    encounterId: "mau_mild_chest_pain_trop_rise",
    timeToDeterioration: 35,
    vague: true,
    regSense: false,
    weight: 9,
    phases: ["early", "deep", "pre_handover"],
    ignored: {
      patientSafety: -4,
      reputation: -1,
      dangerousDelays: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -6,
    },
    handledWell: {
      patientSafety: 4,
      reputation: 1,
      focus: -1,
      stamina: -1,
      clinicalConfidence: 2,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 6,
    },
    delegableTo: ["trusted_fy2"],
    riskyDelegateTo: ["fy1", "locum_no_login"],
    delegationDuration: { trusted_fy2: 12 },
  },
  {
    id: "elderly_slightly_more_confused",
    locationId: "elderly",
    message:
      "Patient a bit more confused than baseline, obs machine not available yet",
    sender: "Elderly care nurse",
    source: "pager",
    claimedUrgency: "non-urgent review",
    trueUrgency: "high",
    category: "ambiguous",
    encounterId: "elderly_occult_sepsis",
    timeToDeterioration: 45,
    vague: true,
    regSense: false,
    weight: 9,
    phases: ["deep", "pre_handover"],
    ignored: {
      patientSafety: -4,
      reputation: -1,
      dangerousDelays: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -6,
    },
    handledWell: {
      patientSafety: 4,
      reputation: 1,
      focus: -1,
      stamina: -1,
      clinicalConfidence: 2,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 6,
    },
    delegableTo: ["trusted_fy2"],
    riskyDelegateTo: ["fy1"],
    delegationDuration: { trusted_fy2: 10 },
  },
  {
    id: "surgical_abnormal_lft_unowned",
    locationId: "surgical",
    message: "Surgical ward has abnormal bloods nobody owns, bilirubin 78",
    sender: "Night coordinator",
    source: "pager",
    claimedUrgency: "please tidy before morning",
    trueUrgency: "high",
    category: "ambiguous",
    encounterId: "surgical_ascending_cholangitis",
    timeToDeterioration: 60,
    vague: true,
    regSense: false,
    weight: 8,
    phases: ["deep", "pre_handover"],
    ignored: {
      patientSafety: -3,
      reputation: -1,
      dangerousDelays: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -5,
    },
    handledWell: {
      patientSafety: 3,
      reputation: 1,
      focus: -1,
      stamina: -1,
      clinicalConfidence: 2,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 5,
    },
    delegableTo: ["trusted_fy2"],
    riskyDelegateTo: ["fy1", "locum_no_login"],
    delegationDuration: { trusted_fy2: 14 },
  },
  {
    id: "resp_small_oxygen_increase",
    locationId: "respiratory",
    message: "Oxygen gone from 2L to 4L, nurse says otherwise comfortable",
    sender: "Respiratory nurse",
    source: "pager",
    claimedUrgency: "routine review",
    trueUrgency: "high",
    category: "ambiguous",
    encounterId: "resp_silent_deterioration",
    timeToDeterioration: 40,
    vague: true,
    regSense: false,
    weight: 9,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -4,
      reputation: -1,
      dangerousDelays: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -6,
    },
    handledWell: {
      patientSafety: 4,
      reputation: 1,
      focus: -1,
      stamina: -1,
      clinicalConfidence: 2,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 6,
    },
    delegableTo: ["trusted_fy2"],
    riskyDelegateTo: ["fy1"],
    delegationDuration: { trusted_fy2: 10 },
  },
  {
    id: "mau_low_sodium_drowsy",
    locationId: "mau",
    message: "Na 116 on admission bloods, patient sleepy but had zopiclone",
    sender: "MAU FY1",
    source: "pager",
    claimedUrgency: "bloods advice",
    trueUrgency: "high",
    category: "ambiguous",
    encounterId: "mau_severe_hyponatraemia",
    timeToDeterioration: 30,
    vague: true,
    regSense: false,
    weight: 9,
    phases: ["early", "deep", "pre_handover"],
    ignored: {
      patientSafety: -4,
      reputation: -1,
      dangerousDelays: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -6,
    },
    handledWell: {
      patientSafety: 4,
      reputation: 1,
      focus: -1,
      stamina: -1,
      clinicalConfidence: 2,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 6,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login"],
    delegationDuration: {},
  },
  {
    id: "cardiology_post_pci_sweaty",
    locationId: "cardiology",
    message: "Post-PCI patient sweaty and anxious, ECG machine being borrowed",
    sender: "Cardiology nurse",
    source: "pager",
    claimedUrgency: "review after ED if possible",
    trueUrgency: "critical",
    category: "ambiguous",
    encounterId: "cardiology_stent_thrombosis",
    timeToDeterioration: 15,
    vague: true,
    regSense: false,
    weight: 11,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -5,
      reputation: -2,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -8,
    },
    handledWell: {
      patientSafety: 5,
      reputation: 2,
      focus: -1,
      stamina: -2,
      clinicalConfidence: 3,
      handoverQuality: 1,
      chaosSurvived: 2,
      score: 8,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login"],
    delegationDuration: {},
  },
  {
    id: "ed_quiet_abdominal_pain",
    locationId: "ed_resus",
    message: "ED says abdominal pain patient looks grey, lactate 5 but BP okay",
    sender: "ED nurse in charge",
    source: "pager",
    claimedUrgency: "medical opinion",
    trueUrgency: "critical",
    category: "ambiguous",
    encounterId: "ed_mesenteric_ischaemia",
    timeToDeterioration: 20,
    vague: true,
    regSense: false,
    weight: 11,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -5,
      reputation: -2,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -8,
    },
    handledWell: {
      patientSafety: 5,
      reputation: 2,
      focus: -1,
      stamina: -2,
      clinicalConfidence: 3,
      handoverQuality: 1,
      chaosSurvived: 2,
      score: 8,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login"],
    delegationDuration: {},
  },
  {
    id: "elderly_wandering_anticoagulated",
    locationId: "elderly",
    message:
      "Confused patient found wandering after unwitnessed fall, on apixaban",
    sender: "Elderly care nurse",
    source: "pager",
    claimedUrgency: "fall review form",
    trueUrgency: "high",
    category: "ambiguous",
    encounterId: "elderly_head_injury_anticoagulated",
    timeToDeterioration: 50,
    vague: false,
    regSense: false,
    weight: 8,
    phases: ["deep", "pre_handover"],
    ignored: {
      patientSafety: -3,
      reputation: -1,
      dangerousDelays: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -5,
    },
    handledWell: {
      patientSafety: 3,
      reputation: 1,
      focus: -1,
      stamina: -1,
      clinicalConfidence: 2,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 5,
    },
    delegableTo: ["trusted_fy2"],
    riskyDelegateTo: ["fy1", "locum_no_login"],
    delegationDuration: { trusted_fy2: 12 },
  },
  {
    id: "ward_warfarin_prescription",
    locationId: "elderly",
    message: "Please prescribe tonight's warfarin, INR 2.4",
    sender: "Ward nurse",
    source: "pager",
    claimedUrgency: "routine prescription",
    trueUrgency: "medium",
    category: "routine",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 5,
    phases: ["early", "deep"],
    ignored: { patientSafety: -1, reputation: -1, pagerBacklog: 1, score: -2 },
    handledWell: { patientSafety: 1, reputation: 1, score: 2 },
    delegableTo: ["fy1", "trusted_fy2"],
    riskyDelegateTo: ["locum_no_login"],
    delegationDuration: { fy1: 8, trusted_fy2: 6 },
  },
  {
    id: "mau_discharge_tto_query",
    locationId: "mau",
    message: "Discharge TTO missing inhaler, patient transport booked for 0700",
    sender: "MAU nurse",
    source: "pager",
    claimedUrgency: "please sort overnight",
    trueUrgency: "medium",
    category: "routine",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 5,
    phases: ["pre_handover"],
    ignored: {
      patientSafety: -1,
      reputation: -1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -3,
    },
    handledWell: {
      patientSafety: 1,
      reputation: 1,
      handoverQuality: 1,
      score: 3,
    },
    delegableTo: ["fy1", "trusted_fy2", "locum_no_login"],
    riskyDelegateTo: [],
    delegationDuration: { fy1: 12, trusted_fy2: 8, locum_no_login: 18 },
  },
  {
    id: "pharmacy_missing_antibiotic_stop_date",
    locationId: "pharmacy",
    message: "Antibiotic review box blank for patient on day 5 co-amoxiclav",
    sender: "On-call pharmacist",
    source: "pager",
    claimedUrgency: "stewardship query",
    trueUrgency: "medium",
    category: "routine",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 4,
    phases: ["early", "pre_handover"],
    ignored: { patientSafety: -1, pagerBacklog: 1, score: -1 },
    handledWell: { patientSafety: 1, reputation: 1, score: 2 },
    delegableTo: ["fy1", "trusted_fy2"],
    riskyDelegateTo: ["locum_no_login"],
    delegationDuration: { fy1: 10, trusted_fy2: 8 },
  },
  {
    id: "resp_neb_frequency",
    locationId: "respiratory",
    message: "Can salbutamol nebs be changed from PRN to regular overnight",
    sender: "Respiratory nurse",
    source: "pager",
    claimedUrgency: "prescribing request",
    trueUrgency: "medium",
    category: "routine",
    encounterId: null,
    timeToDeterioration: 120,
    vague: false,
    regSense: false,
    weight: 5,
    phases: ["early", "deep"],
    ignored: { patientSafety: -1, pagerBacklog: 1, score: -1 },
    handledWell: { patientSafety: 1, reputation: 1, score: 2 },
    delegableTo: ["fy1", "trusted_fy2"],
    riskyDelegateTo: [],
    delegationDuration: { fy1: 8, trusted_fy2: 6 },
  },
  {
    id: "relatives_update_waiting",
    locationId: "elderly",
    message: "Relatives asking for update before they leave, patient stable",
    sender: "Ward nurse",
    source: "pager",
    claimedUrgency: "family waiting",
    trueUrgency: "low",
    category: "routine",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 4,
    phases: ["early"],
    ignored: { reputation: -1, pagerBacklog: 1, score: -1 },
    handledWell: { reputation: 2, focus: -1, stamina: -1, score: 1 },
    delegableTo: ["trusted_fy2"],
    riskyDelegateTo: ["fy1", "locum_no_login"],
    delegationDuration: { trusted_fy2: 15 },
  },
  {
    id: "cannula_for_iv_fluids",
    locationId: "mau",
    message: "Cannula tissued, needs IV fluids overnight",
    sender: "MAU nurse",
    source: "pager",
    claimedUrgency: "cannula please",
    trueUrgency: "medium",
    category: "routine",
    encounterId: null,
    timeToDeterioration: 120,
    vague: false,
    regSense: false,
    weight: 5,
    phases: ["early", "deep"],
    ignored: { patientSafety: -1, reputation: -1, pagerBacklog: 1, score: -2 },
    handledWell: {
      patientSafety: 1,
      reputation: 1,
      focus: -1,
      stamina: -1,
      score: 1,
    },
    delegableTo: ["fy1", "trusted_fy2", "locum_no_login"],
    riskyDelegateTo: [],
    delegationDuration: { fy1: 12, trusted_fy2: 8, locum_no_login: 20 },
  },
  {
    id: "routine_vte_risk",
    locationId: "surgical",
    message: "VTE assessment missing for medical outlier on surgical ward",
    sender: "Surgical ward nurse",
    source: "pager",
    claimedUrgency: "needs completing tonight",
    trueUrgency: "medium",
    category: "routine",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 4,
    phases: ["early", "deep", "pre_handover"],
    ignored: { patientSafety: -1, pagerBacklog: 1, score: -1 },
    handledWell: { patientSafety: 1, reputation: 1, score: 2 },
    delegableTo: ["fy1", "trusted_fy2", "locum_no_login"],
    riskyDelegateTo: [],
    delegationDuration: { fy1: 8, trusted_fy2: 6, locum_no_login: 12 },
  },
  {
    id: "insulin_sliding_scale_review",
    locationId: "mau",
    message: "Variable rate insulin prescription expires at 0400",
    sender: "MAU nurse",
    source: "pager",
    claimedUrgency: "please review",
    trueUrgency: "medium",
    category: "routine",
    encounterId: null,
    timeToDeterioration: 90,
    vague: false,
    regSense: false,
    weight: 6,
    phases: ["deep"],
    ignored: { patientSafety: -2, reputation: -1, pagerBacklog: 1, score: -3 },
    handledWell: {
      patientSafety: 2,
      reputation: 1,
      clinicalConfidence: 1,
      score: 3,
    },
    delegableTo: ["trusted_fy2"],
    riskyDelegateTo: ["fy1", "locum_no_login"],
    delegationDuration: { trusted_fy2: 8 },
  },
  {
    id: "urgent_paracetamol_renewal",
    locationId: "elderly",
    message: "Urgent: paracetamol not prescribed and patient wants it now",
    sender: "Ward nurse",
    source: "pager",
    claimedUrgency: "urgent",
    trueUrgency: "low",
    category: "inappropriate",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 4,
    phases: ["deep"],
    ignored: { reputation: -1, pagerBacklog: 1, inappropriateAvoided: 1 },
    handledWell: { reputation: 1, focus: -1 },
    delegableTo: ["fy1", "trusted_fy2", "locum_no_login"],
    riskyDelegateTo: [],
    delegationDuration: { fy1: 6, trusted_fy2: 5, locum_no_login: 10 },
  },
  {
    id: "sleeping_tablet_request",
    locationId: "surgical",
    message: "Patient asking for zopiclone, never had it before",
    sender: "Surgical ward nurse",
    source: "pager",
    claimedUrgency: "urgent patient request",
    trueUrgency: "low",
    category: "inappropriate",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 4,
    phases: ["deep"],
    ignored: { reputation: -1, pagerBacklog: 1, inappropriateAvoided: 1 },
    handledWell: { reputation: 1, focus: -1 },
    delegableTo: ["fy1", "trusted_fy2"],
    riskyDelegateTo: ["locum_no_login"],
    delegationDuration: { fy1: 8, trusted_fy2: 6 },
  },
  {
    id: "discharge_summary_2019",
    locationId: "mau",
    message:
      "Can you rewrite a 2019 discharge summary because clinic cannot find it",
    sender: "Site admin message",
    source: "system",
    claimedUrgency: "urgent admin",
    trueUrgency: "nonsense",
    category: "inappropriate",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 4,
    phases: ["early", "deep", "pre_handover"],
    ignored: { focus: 1, inappropriateAvoided: 1, score: 2 },
    handledWell: { focus: -2, stamina: -1, score: -2 },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login"],
    delegationDuration: {},
  },
  {
    id: "routine_sick_note",
    locationId: "elderly",
    message: "Relative asking for fit note for patient's son's employer",
    sender: "Ward clerk",
    source: "pager",
    claimedUrgency: "needs doing tonight",
    trueUrgency: "nonsense",
    category: "inappropriate",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 4,
    phases: ["early", "pre_handover"],
    ignored: { focus: 1, inappropriateAvoided: 1, score: 2 },
    handledWell: { focus: -1, stamina: -1, score: -1 },
    delegableTo: ["fy1"],
    riskyDelegateTo: [],
    delegationDuration: { fy1: 12 },
  },
  {
    id: "urgent_fluid_balance_rewrite",
    locationId: "respiratory",
    message: "Urgent: fluid balance chart is messy, can you rewrite totals",
    sender: "Ward nurse",
    source: "pager",
    claimedUrgency: "urgent",
    trueUrgency: "low",
    category: "inappropriate",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 4,
    phases: ["deep", "pre_handover"],
    ignored: { focus: 1, inappropriateAvoided: 1, score: 2 },
    handledWell: { focus: -1, stamina: -1, score: -1 },
    delegableTo: ["fy1", "locum_no_login"],
    riskyDelegateTo: [],
    delegationDuration: { fy1: 10, locum_no_login: 14 },
  },
  {
    id: "bed_manager_clinical_priority_form",
    locationId: "mau",
    message:
      "Can you rank all medical outliers by discharge likelihood before 0600",
    sender: "Bed manager",
    source: "pager",
    claimedUrgency: "urgent bed pressure",
    trueUrgency: "low",
    category: "inappropriate",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 5,
    phases: ["deep", "pre_handover"],
    ignored: {
      reputation: -1,
      focus: 1,
      chaosSurvived: 1,
      inappropriateAvoided: 1,
      score: 2,
    },
    handledWell: { reputation: 1, focus: -2, stamina: -1, score: -1 },
    delegableTo: ["bed_manager"],
    riskyDelegateTo: ["fy1", "trusted_fy2"],
    delegationDuration: { bed_manager: 7 },
  },
  {
    id: "epr_downtime_results",
    locationId: "mau",
    message:
      "EPR downtime, lab results printing in ED only, nobody knows whose potassium is high",
    sender: "Night coordinator",
    source: "system",
    claimedUrgency: "systems issue",
    trueUrgency: "high",
    category: "urgent",
    encounterId: null,
    timeToDeterioration: 45,
    vague: true,
    regSense: true,
    weight: 9,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -3,
      reputation: -2,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 2,
      handoverQuality: -2,
      score: -7,
    },
    handledWell: {
      patientSafety: 3,
      reputation: 2,
      focus: -2,
      stamina: -2,
      clinicalConfidence: 1,
      handoverQuality: 2,
      chaosSurvived: 2,
      score: 7,
    },
    delegableTo: ["trusted_fy2", "bed_manager"],
    riskyDelegateTo: ["fy1", "locum_no_login"],
    delegationDuration: { trusted_fy2: 20, bed_manager: 15 },
  },
  {
    id: "missing_drug_chart",
    locationId: "elderly",
    message:
      "Drug chart missing for bay patient due IV antibiotics and insulin",
    sender: "Ward nurse",
    source: "pager",
    claimedUrgency: "chart missing",
    trueUrgency: "high",
    category: "urgent",
    encounterId: null,
    timeToDeterioration: 60,
    vague: false,
    regSense: false,
    weight: 8,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -3,
      reputation: -1,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -5,
    },
    handledWell: {
      patientSafety: 3,
      reputation: 1,
      focus: -1,
      stamina: -1,
      clinicalConfidence: 1,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 5,
    },
    delegableTo: ["fy1", "trusted_fy2"],
    riskyDelegateTo: ["locum_no_login"],
    delegationDuration: { fy1: 15, trusted_fy2: 10 },
  },
  {
    id: "radiology_ct_pushback",
    locationId: "radiology",
    message:
      "Radiology wants consultant name before scanning drowsy patient with headache",
    sender: "Radiology coordinator",
    source: "pager",
    claimedUrgency: "protocol query",
    trueUrgency: "high",
    category: "urgent",
    encounterId: null,
    timeToDeterioration: 40,
    vague: true,
    regSense: true,
    weight: 8,
    phases: ["early", "deep", "pre_handover"],
    ignored: {
      patientSafety: -3,
      reputation: -2,
      dangerousDelays: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -6,
    },
    handledWell: {
      patientSafety: 3,
      reputation: 2,
      focus: -1,
      stamina: -1,
      clinicalConfidence: 1,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 6,
    },
    delegableTo: ["trusted_fy2"],
    riskyDelegateTo: ["fy1", "locum_no_login"],
    delegationDuration: { trusted_fy2: 8 },
  },
  {
    id: "printer_failure_drug_round",
    locationId: "pharmacy",
    message:
      "Ward printer failed, nurses cannot print replacement insulin chart",
    sender: "Night coordinator",
    source: "system",
    claimedUrgency: "IT issue",
    trueUrgency: "medium",
    category: "urgent",
    encounterId: null,
    timeToDeterioration: 120,
    vague: false,
    regSense: true,
    weight: 6,
    phases: ["deep", "pre_handover"],
    ignored: {
      patientSafety: -2,
      reputation: -1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -3,
    },
    handledWell: {
      patientSafety: 2,
      reputation: 1,
      focus: -1,
      stamina: -1,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 4,
    },
    delegableTo: ["fy1", "trusted_fy2", "bed_manager"],
    riskyDelegateTo: [],
    delegationDuration: { fy1: 12, trusted_fy2: 8, bed_manager: 10 },
  },
  {
    id: "blood_gas_analyser_broken",
    locationId: "mau",
    message:
      "Blood gas analyser rejecting all samples, ED says use theirs only for resus",
    sender: "MAU nurse in charge",
    source: "system",
    claimedUrgency: "equipment issue",
    trueUrgency: "medium",
    category: "urgent",
    encounterId: null,
    timeToDeterioration: 90,
    vague: false,
    regSense: true,
    weight: 7,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -2,
      reputation: -1,
      pagerBacklog: 2,
      handoverQuality: -1,
      score: -4,
    },
    handledWell: {
      patientSafety: 2,
      reputation: 1,
      focus: -1,
      stamina: -1,
      handoverQuality: 1,
      chaosSurvived: 2,
      score: 5,
    },
    delegableTo: ["trusted_fy2", "bed_manager"],
    riskyDelegateTo: ["fy1"],
    delegationDuration: { trusted_fy2: 15, bed_manager: 10 },
  },
  {
    id: "no_cannulas_hospital",
    locationId: "pharmacy",
    message:
      "No green cannulas left on MAU, stores locked, three IV starts pending",
    sender: "MAU nurse in charge",
    source: "system",
    claimedUrgency: "stock issue",
    trueUrgency: "medium",
    category: "urgent",
    encounterId: null,
    timeToDeterioration: 120,
    vague: false,
    regSense: true,
    weight: 6,
    phases: ["early", "deep", "pre_handover"],
    ignored: {
      patientSafety: -2,
      reputation: -1,
      pagerBacklog: 2,
      handoverQuality: -1,
      score: -4,
    },
    handledWell: {
      patientSafety: 2,
      reputation: 1,
      focus: -1,
      stamina: -1,
      handoverQuality: 1,
      chaosSurvived: 2,
      score: 5,
    },
    delegableTo: ["fy1", "trusted_fy2", "bed_manager"],
    riskyDelegateTo: [],
    delegationDuration: { fy1: 15, trusted_fy2: 10, bed_manager: 8 },
  },
  {
    id: "estates_ceiling_leak",
    locationId: "estates",
    message:
      "Ceiling leak over corridor outside side room, patient notes getting damp",
    sender: "Site practitioner",
    source: "pager",
    claimedUrgency: "estates aware, need clinical decision",
    trueUrgency: "low",
    category: "urgent",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: true,
    weight: 5,
    phases: ["deep"],
    ignored: { patientSafety: -1, reputation: -1, pagerBacklog: 1, score: -2 },
    handledWell: {
      patientSafety: 1,
      reputation: 1,
      focus: -1,
      chaosSurvived: 1,
      score: 2,
    },
    delegableTo: ["bed_manager"],
    riskyDelegateTo: ["fy1"],
    delegationDuration: { bed_manager: 7 },
  },
  {
    id: "mess_fridge_alarm",
    locationId: "mess",
    message: "Mess fridge alarm going off, sandwiches at risk",
    sender: "Unknown bleep",
    source: "pager",
    claimedUrgency: "urgent facilities issue",
    trueUrgency: "nonsense",
    category: "absurd",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 4,
    phases: ["deep"],
    ignored: { focus: 1, chaosSurvived: 1, inappropriateAvoided: 1, score: 2 },
    handledWell: { focus: -1, stamina: -1, chaosSurvived: 1 },
    delegableTo: ["bed_manager"],
    riskyDelegateTo: ["fy1", "trusted_fy2"],
    delegationDuration: { bed_manager: 7 },
  },
  {
    id: "corridor_pigeon",
    locationId: "corridor",
    message:
      "There is a pigeon outside AMU bay 3 and infection control are not answering",
    sender: "Porter",
    source: "pager",
    claimedUrgency: "urgent infection control",
    trueUrgency: "nonsense",
    category: "absurd",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 4,
    phases: ["early", "deep"],
    ignored: { focus: 1, chaosSurvived: 1, inappropriateAvoided: 1, score: 2 },
    handledWell: { focus: -1, chaosSurvived: 1 },
    delegableTo: ["bed_manager"],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login"],
    delegationDuration: { bed_manager: 7 },
  },
  {
    id: "lifts_duck_family",
    locationId: "lifts",
    message: "Lift B stuck open with a duck and three ducklings inside",
    sender: "Security",
    source: "pager",
    claimedUrgency: "major incident pending",
    trueUrgency: "nonsense",
    category: "absurd",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 4,
    phases: ["deep", "pre_handover"],
    ignored: { focus: 1, chaosSurvived: 1, inappropriateAvoided: 1, score: 2 },
    handledWell: { focus: -1, chaosSurvived: 1 },
    delegableTo: ["bed_manager"],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login"],
    delegationDuration: { bed_manager: 7 },
  },
];

export const bleepPackTasks: TaskTemplate[] = rawBleepPack.map(
  ({ encounterId, ...task }) => {
    const mappedEncounterId = encounterId
      ? encounterMap[encounterId]
      : undefined;
    return mappedEncounterId
      ? { ...task, encounterId: mappedEncounterId }
      : task;
  },
);
