import type { TaskTemplate } from "./types";

type RawBleepPackItem = Omit<TaskTemplate, "encounterId"> & {
  encounterId?: string | null;
};

const encounterMap: Record<string, string | undefined> = {
  ed_hypotensive_sepsis: "occult_sepsis_adrenal_crisis",
  resp_acute_hypercapnia: "hypercapnic_drowsiness_oxygen",
  cardiology_wide_complex_tachy: "broad_complex_tachy",
  elderly_stroke_thrombolysis_window: "stroke_mimic",
  surgical_upper_gi_bleed: "ugi_bleed",
  mau_dka_new_diagnosis: "dka",
  pharmacy_potassium_critical: "aki_hyperkalaemia",
  radiology_ctpa_massive_pe: "pe_shock_pregnancy_postpartum",
  mau_mild_chest_pain_trop_rise: "nstemi",
  resp_small_oxygen_increase: "hypercapnic_drowsiness_oxygen",
  mau_low_sodium_drowsy: "hyponatraemia_seizure_desmopressin",
  ed_quiet_abdominal_pain: "occult_sepsis_adrenal_crisis",
  elderly_wandering_anticoagulated: "stroke_mimic",
};

const rawBleepPack: RawBleepPackItem[] = [
  {
    id: "ed_hypotensive_sepsis",
    locationId: "ed_resus",
    message: "ED asking if you can review ?sepsis, BP 82 systolic after fluids",
    revealAtIntel2:
      "Full picture: 67F, three days of rigors and confusion. CRP 280, lactate 3.8. Likely gram-negative sepsis — needs senior review now.",
    sender: "ED SHO",
    source: "pager",
    claimedUrgency: "urgent review when free",
    trueUrgency: "critical",
    category: "emergency",
    encounterId: "ed_hypotensive_sepsis",
    timeToDeterioration: 10,
    vague: false,
    regSense: false,
    weight: 12,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -5,
      reputation: -2,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -8,
    },
    handledWell: {
      patientSafety: 5,
      reputation: 2,
      focus: -1,
      stamina: -2,
      clinicalConfidence: 3,
      handoverQuality: 1,
      chaosSurvived: 2,
      score: 8,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2"],
    delegationDuration: {},
  },
  {
    id: "resp_acute_hypercapnia",
    locationId: "respiratory",
    message: "Ward asking about drowsy COPD patient, gas just back",
    revealAtIntel1:
      "Called back — the nurse reports the patient is increasingly drowsy, pH 7.24, pCO2 9.1, RR 8. She says 'he's not right'.",
    revealAtIntel2:
      "Full picture: 71M known COPD, now barely rousable, with type 2 respiratory failure on the gas. Needs urgent NIV and ICU awareness — not a routine NIV plan.",
    sender: "Respiratory nurse",
    source: "pager",
    claimedUrgency: "can you advise NIV plan",
    trueUrgency: "critical",
    category: "emergency",
    encounterId: "resp_acute_hypercapnia",
    timeToDeterioration: 15,
    vague: true,
    regSense: false,
    weight: 11,
    phases: ["early", "deep", "pre_handover"],
    ignored: {
      patientSafety: -5,
      reputation: -2,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -8,
    },
    handledWell: {
      patientSafety: 5,
      reputation: 2,
      focus: -1,
      stamina: -2,
      clinicalConfidence: 3,
      handoverQuality: 1,
      chaosSurvived: 2,
      score: 8,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "locum_no_login"],
    delegationDuration: {},
  },
  {
    id: "cardiology_wide_complex_tachy",
    locationId: "cardiology",
    message:
      "Patient on CCU monitor in broad complex tachycardia, nurse wants review",
    revealAtIntel2:
      "Full picture: sustained broad-complex tachycardia at 180, BP dropping, chest tight. Treat as VT — needs senior support and pads on now.",
    sender: "CCU nurse",
    source: "pager",
    claimedUrgency: "urgent",
    trueUrgency: "critical",
    category: "emergency",
    encounterId: "cardiology_wide_complex_tachy",
    timeToDeterioration: 10,
    vague: false,
    regSense: false,
    weight: 12,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -5,
      reputation: -3,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -9,
    },
    handledWell: {
      patientSafety: 5,
      reputation: 3,
      focus: -1,
      stamina: -2,
      clinicalConfidence: 3,
      handoverQuality: 1,
      chaosSurvived: 2,
      score: 9,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2"],
    delegationDuration: {},
  },
  {
    id: "mau_anaphylaxis_antibiotic",
    locationId: "mau",
    message:
      "New rash and wheeze after IV antibiotic, nurse asking if chlorphenamine enough",
    revealAtIntel2:
      "Full picture: spreading urticaria, audible wheeze and a falling BP minutes after IV co-amoxiclav. This is anaphylaxis — IM adrenaline now, chlorphenamine is not enough.",
    sender: "MAU nurse",
    source: "pager",
    claimedUrgency: "quick advice",
    trueUrgency: "critical",
    category: "emergency",
    encounterId: "mau_anaphylaxis_antibiotic",
    timeToDeterioration: 10,
    vague: false,
    regSense: false,
    weight: 12,
    phases: ["early", "deep", "pre_handover"],
    ignored: {
      patientSafety: -5,
      reputation: -2,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -8,
    },
    handledWell: {
      patientSafety: 5,
      reputation: 2,
      focus: -1,
      stamina: -1,
      clinicalConfidence: 3,
      handoverQuality: 1,
      chaosSurvived: 2,
      score: 8,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2"],
    delegationDuration: {},
  },
  {
    id: "elderly_stroke_thrombolysis_window",
    locationId: "elderly",
    message: "New facial droop noticed on bay, last seen well maybe midnight",
    revealAtIntel1:
      "Reviewed — left facial droop and slurred speech, obs otherwise stable. The nurse is now unsure exactly when last seen normal; it could be inside the thrombolysis window.",
    revealAtIntel2:
      "Full picture: 78M, NIHSS 6, last definitely well 23:40, glucose normal, no anticoagulants. Possible thrombolysis candidate but could be a mimic — needs urgent CT and the stroke team now.",
    sender: "Ward nurse",
    source: "pager",
    claimedUrgency: "doctor review please",
    trueUrgency: "high",
    category: "urgent",
    encounterId: "elderly_stroke_thrombolysis_window",
    timeToDeterioration: 25,
    vague: true,
    regSense: false,
    weight: 10,
    phases: ["deep", "pre_handover"],
    ignored: {
      patientSafety: -4,
      reputation: -2,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -7,
    },
    handledWell: {
      patientSafety: 4,
      reputation: 2,
      focus: -1,
      stamina: -1,
      clinicalConfidence: 2,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 7,
    },
    delegableTo: ["trusted_fy2"],
    riskyDelegateTo: ["fy1", "locum_no_login"],
    delegationDuration: { trusted_fy2: 8 },
  },
  {
    id: "surgical_upper_gi_bleed",
    locationId: "surgical",
    message:
      "Surgical outlier vomiting coffee grounds, Hb dropped since evening",
    revealAtIntel2:
      "Full picture: ongoing coffee-ground vomiting, Hb down 22 points, tachycardic. An active upper GI bleed — needs IV access, a crossmatch and an endoscopy referral.",
    sender: "Surgical ward nurse",
    source: "pager",
    claimedUrgency: "medical review requested",
    trueUrgency: "high",
    category: "urgent",
    encounterId: "surgical_upper_gi_bleed",
    timeToDeterioration: 20,
    vague: false,
    regSense: false,
    weight: 10,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -4,
      reputation: -2,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -7,
    },
    handledWell: {
      patientSafety: 4,
      reputation: 2,
      focus: -1,
      stamina: -2,
      clinicalConfidence: 2,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 7,
    },
    delegableTo: ["trusted_fy2"],
    riskyDelegateTo: ["fy1", "locum_no_login"],
    delegationDuration: { trusted_fy2: 10 },
  },
  {
    id: "mau_dka_new_diagnosis",
    locationId: "mau",
    message: "Ketones 6.2 on new diabetic admission, nurse asking for fluids",
    revealAtIntel2:
      "Full picture: ketones 6.2, glucose 28, pH 7.21, bicarb 12 — established DKA. Needs fixed-rate insulin and the full DKA protocol, not just fluids.",
    sender: "MAU nurse",
    source: "pager",
    claimedUrgency: "urgent prescription",
    trueUrgency: "high",
    category: "urgent",
    encounterId: "mau_dka_new_diagnosis",
    timeToDeterioration: 30,
    vague: false,
    regSense: false,
    weight: 10,
    phases: ["early", "deep", "pre_handover"],
    ignored: {
      patientSafety: -4,
      reputation: -2,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -7,
    },
    handledWell: {
      patientSafety: 4,
      reputation: 2,
      focus: -1,
      stamina: -2,
      clinicalConfidence: 2,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 7,
    },
    delegableTo: ["trusted_fy2"],
    riskyDelegateTo: ["fy1", "locum_no_login"],
    delegationDuration: { trusted_fy2: 12 },
  },
  {
    id: "icu_unexpected_stepdown_decline",
    locationId: "icu",
    message: "ICU outreach asking you to see recent stepdown, NEWS now 9",
    revealAtIntel2:
      "Full picture: NEWS 9 driven by a rising respiratory rate and falling sats on a recent stepdown — an early failed stepdown. Needs joint review and likely ICU readmission.",
    sender: "ICU outreach nurse",
    source: "pager",
    claimedUrgency: "joint review",
    trueUrgency: "high",
    category: "urgent",
    encounterId: "icu_unexpected_stepdown_decline",
    timeToDeterioration: 20,
    vague: false,
    regSense: false,
    weight: 10,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -4,
      reputation: -2,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -7,
    },
    handledWell: {
      patientSafety: 4,
      reputation: 2,
      focus: -1,
      stamina: -2,
      clinicalConfidence: 2,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 7,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login"],
    delegationDuration: {},
  },
  {
    id: "pharmacy_potassium_critical",
    locationId: "pharmacy",
    message: "Lab phoned K 6.9, sample not haemolysed, patient on renal ward",
    revealAtIntel2:
      "Full picture: K 6.9, non-haemolysed, on a renal patient with ECG changes. A true hyperkalaemic emergency — calcium gluconate and insulin-dextrose now.",
    sender: "On-call pharmacist",
    source: "pager",
    claimedUrgency: "please action tonight",
    trueUrgency: "high",
    category: "urgent",
    encounterId: "pharmacy_potassium_critical",
    timeToDeterioration: 25,
    vague: false,
    regSense: false,
    weight: 10,
    phases: ["early", "deep", "pre_handover"],
    ignored: {
      patientSafety: -4,
      reputation: -2,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -7,
    },
    handledWell: {
      patientSafety: 4,
      reputation: 2,
      focus: -1,
      stamina: -1,
      clinicalConfidence: 2,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 7,
    },
    delegableTo: ["trusted_fy2"],
    riskyDelegateTo: ["fy1", "locum_no_login"],
    delegationDuration: { trusted_fy2: 8 },
  },
  {
    id: "radiology_ctpa_massive_pe",
    locationId: "radiology",
    message:
      "Radiology asking who is taking responsibility for large saddle PE report",
    revealAtIntel1:
      "Called radiology — the CTPA shows a large saddle PE. The patient is a postnatal woman on the ward, currently tachycardic and breathless, and nobody has actioned it.",
    revealAtIntel2:
      "Full picture: 32F, five days postpartum, HR 120, BP 88 systolic, hypoxic. Saddle PE with RV strain — high-risk PE with shock. Needs immediate senior input on thrombolysis.",
    sender: "Radiology registrar",
    source: "pager",
    claimedUrgency: "please clarify team",
    trueUrgency: "critical",
    category: "emergency",
    encounterId: "radiology_ctpa_massive_pe",
    timeToDeterioration: 15,
    vague: true,
    regSense: false,
    weight: 11,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -5,
      reputation: -2,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -8,
    },
    handledWell: {
      patientSafety: 5,
      reputation: 2,
      focus: -1,
      stamina: -2,
      clinicalConfidence: 3,
      handoverQuality: 1,
      chaosSurvived: 2,
      score: 8,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login"],
    delegationDuration: {},
  },
  {
    id: "mau_mild_chest_pain_trop_rise",
    locationId: "mau",
    message: "Chest pain settled, repeat trop has gone up a bit",
    revealAtIntel1:
      "Looked at it — troponin has risen from 18 to 320 and the ECG now shows new T-wave inversion in the lateral leads. Not as benign as it sounded.",
    revealAtIntel2:
      "Full picture: 64M with a dynamic troponin and evolving ECG changes — this is an NSTEMI. Needs antiplatelets, anticoagulation and a cardiology referral, not routine advice.",
    sender: "MAU FY1",
    source: "pager",
    claimedUrgency: "routine senior advice",
    trueUrgency: "high",
    category: "ambiguous",
    encounterId: "mau_mild_chest_pain_trop_rise",
    timeToDeterioration: 35,
    vague: true,
    regSense: false,
    weight: 9,
    phases: ["early", "deep", "pre_handover"],
    ignored: {
      patientSafety: -4,
      reputation: -1,
      dangerousDelays: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -6,
    },
    handledWell: {
      patientSafety: 4,
      reputation: 1,
      focus: -1,
      stamina: -1,
      clinicalConfidence: 2,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 6,
    },
    delegableTo: ["trusted_fy2"],
    riskyDelegateTo: ["fy1", "locum_no_login"],
    delegationDuration: { trusted_fy2: 12 },
  },
  {
    id: "elderly_slightly_more_confused",
    locationId: "elderly",
    message:
      "Patient a bit more confused than baseline, obs machine not available yet",
    revealAtIntel1:
      "Got obs done — temp 38.6, HR 110, BP 98 systolic. This is more than confusion; she looks septic, though the source isn't obvious yet.",
    revealAtIntel2:
      "Full picture: 84F with new delirium driven by urosepsis — lactate 2.8, CRP high. Needs the sepsis six and review now, not a morning ward-round job.",
    sender: "Elderly care nurse",
    source: "pager",
    claimedUrgency: "non-urgent review",
    trueUrgency: "high",
    category: "ambiguous",
    encounterId: "elderly_occult_sepsis",
    timeToDeterioration: 45,
    vague: true,
    regSense: false,
    weight: 9,
    phases: ["deep", "pre_handover"],
    ignored: {
      patientSafety: -4,
      reputation: -1,
      dangerousDelays: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -6,
    },
    handledWell: {
      patientSafety: 4,
      reputation: 1,
      focus: -1,
      stamina: -1,
      clinicalConfidence: 2,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 6,
    },
    delegableTo: ["trusted_fy2"],
    riskyDelegateTo: ["fy1"],
    delegationDuration: { trusted_fy2: 10 },
  },
  {
    id: "surgical_abnormal_lft_unowned",
    locationId: "surgical",
    message: "Surgical ward has abnormal bloods nobody owns, bilirubin 78",
    revealAtIntel1:
      "Pulled the chart — bilirubin 78, ALP 410, and the patient is febrile at 38.4 with right upper quadrant pain. This isn't just deranged LFTs.",
    revealAtIntel2:
      "Full picture: Charcot's triad — fever, jaundice, RUQ pain — so ascending cholangitis. Needs blood cultures, antibiotics and an urgent surgical/biliary discussion.",
    sender: "Night coordinator",
    source: "pager",
    claimedUrgency: "please tidy before morning",
    trueUrgency: "high",
    category: "ambiguous",
    encounterId: "surgical_ascending_cholangitis",
    timeToDeterioration: 60,
    vague: true,
    regSense: false,
    weight: 8,
    phases: ["deep", "pre_handover"],
    ignored: {
      patientSafety: -3,
      reputation: -1,
      dangerousDelays: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -5,
    },
    handledWell: {
      patientSafety: 3,
      reputation: 1,
      focus: -1,
      stamina: -1,
      clinicalConfidence: 2,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 5,
    },
    delegableTo: ["trusted_fy2"],
    riskyDelegateTo: ["fy1", "locum_no_login"],
    delegationDuration: { trusted_fy2: 14 },
  },
  {
    id: "resp_small_oxygen_increase",
    locationId: "respiratory",
    message: "Oxygen gone from 2L to 4L, nurse says otherwise comfortable",
    revealAtIntel1:
      "Checked — she's actually on 6L now, sats 91%, RR 26. 'Comfortable' was optimistic; something is changing.",
    revealAtIntel2:
      "Full picture: a steadily rising oxygen requirement with a new oxygen-dependent infiltrate — likely evolving pneumonia or aspiration. Needs review, a gas and a chest film now.",
    sender: "Respiratory nurse",
    source: "pager",
    claimedUrgency: "routine review",
    trueUrgency: "high",
    category: "ambiguous",
    encounterId: "resp_silent_deterioration",
    timeToDeterioration: 40,
    vague: true,
    regSense: false,
    weight: 9,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -4,
      reputation: -1,
      dangerousDelays: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -6,
    },
    handledWell: {
      patientSafety: 4,
      reputation: 1,
      focus: -1,
      stamina: -1,
      clinicalConfidence: 2,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 6,
    },
    delegableTo: ["trusted_fy2"],
    riskyDelegateTo: ["fy1"],
    delegationDuration: { trusted_fy2: 10 },
  },
  {
    id: "mau_low_sodium_drowsy",
    locationId: "mau",
    message: "Na 116 on admission bloods, patient sleepy but had zopiclone",
    revealAtIntel1:
      "Reviewed — only rousable to voice, and the drowsiness predates the zopiclone. Sodium is 116. This isn't sedation.",
    revealAtIntel2:
      "Full picture: symptomatic severe hyponatraemia with a dropping GCS and seizure risk. Needs senior input on hypertonic saline and close monitoring — don't correct too fast.",
    sender: "MAU FY1",
    source: "pager",
    claimedUrgency: "bloods advice",
    trueUrgency: "high",
    category: "ambiguous",
    encounterId: "mau_severe_hyponatraemia",
    timeToDeterioration: 30,
    vague: true,
    regSense: false,
    weight: 9,
    phases: ["early", "deep", "pre_handover"],
    ignored: {
      patientSafety: -4,
      reputation: -1,
      dangerousDelays: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -6,
    },
    handledWell: {
      patientSafety: 4,
      reputation: 1,
      focus: -1,
      stamina: -1,
      clinicalConfidence: 2,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 6,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login"],
    delegationDuration: {},
  },
  {
    id: "cardiology_post_pci_sweaty",
    locationId: "cardiology",
    message: "Post-PCI patient sweaty and anxious, ECG machine being borrowed",
    revealAtIntel1:
      "Got an ECG — ST elevation in the territory he was stented this morning. He's sweaty, clammy and in pain. This is acute.",
    revealAtIntel2:
      "Full picture: acute stent thrombosis — re-occlusion of the culprit vessel. A cath-lab emergency. Needs immediate cardiology and reactivation of the primary PCI pathway.",
    sender: "Cardiology nurse",
    source: "pager",
    claimedUrgency: "review after ED if possible",
    trueUrgency: "critical",
    category: "ambiguous",
    encounterId: "cardiology_stent_thrombosis",
    timeToDeterioration: 15,
    vague: true,
    regSense: false,
    weight: 11,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -5,
      reputation: -2,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -8,
    },
    handledWell: {
      patientSafety: 5,
      reputation: 2,
      focus: -1,
      stamina: -2,
      clinicalConfidence: 3,
      handoverQuality: 1,
      chaosSurvived: 2,
      score: 8,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login"],
    delegationDuration: {},
  },
  {
    id: "ed_quiet_abdominal_pain",
    locationId: "ed_resus",
    message: "ED says abdominal pain patient looks grey, lactate 5 but BP okay",
    revealAtIntel1:
      "Reviewed — pain is out of proportion to a soft abdomen, AF on the monitor, lactate now 6.2. BP is holding but he looks awful.",
    revealAtIntel2:
      "Full picture: pain out of proportion plus AF plus a rising lactate is mesenteric ischaemia until proven otherwise. Needs an urgent CT angiogram and surgical referral now.",
    sender: "ED nurse in charge",
    source: "pager",
    claimedUrgency: "medical opinion",
    trueUrgency: "critical",
    category: "ambiguous",
    encounterId: "ed_mesenteric_ischaemia",
    timeToDeterioration: 20,
    vague: true,
    regSense: false,
    weight: 11,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -5,
      reputation: -2,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -8,
    },
    handledWell: {
      patientSafety: 5,
      reputation: 2,
      focus: -1,
      stamina: -2,
      clinicalConfidence: 3,
      handoverQuality: 1,
      chaosSurvived: 2,
      score: 8,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login"],
    delegationDuration: {},
  },
  {
    id: "elderly_wandering_anticoagulated",
    locationId: "elderly",
    message:
      "Confused patient found wandering after unwitnessed fall, on apixaban",
    revealAtIntel1:
      "Looked into it — unwitnessed fall, now a bruise over the temple and more drowsy than baseline, and she's on apixaban. An unwitnessed head injury on a DOAC.",
    revealAtIntel2:
      "Full picture: high-risk head injury on anticoagulation. Needs a CT head within the hour and consideration of reversal if a bleed is found.",
    sender: "Elderly care nurse",
    source: "pager",
    claimedUrgency: "fall review form",
    trueUrgency: "high",
    category: "ambiguous",
    encounterId: "elderly_head_injury_anticoagulated",
    timeToDeterioration: 50,
    vague: false,
    regSense: false,
    weight: 8,
    phases: ["deep", "pre_handover"],
    ignored: {
      patientSafety: -3,
      reputation: -1,
      dangerousDelays: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -5,
    },
    handledWell: {
      patientSafety: 3,
      reputation: 1,
      focus: -1,
      stamina: -1,
      clinicalConfidence: 2,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 5,
    },
    delegableTo: ["trusted_fy2"],
    riskyDelegateTo: ["fy1", "locum_no_login"],
    delegationDuration: { trusted_fy2: 12 },
  },
  {
    id: "ward_warfarin_prescription",
    locationId: "elderly",
    message: "Please prescribe tonight's warfarin, INR 2.4",
    revealAtIntel2:
      "Confirmed — INR 2.4, in range, on a stable maintenance dose. Genuinely routine: prescribe the usual dose, and safe to delegate.",
    sender: "Ward nurse",
    source: "pager",
    claimedUrgency: "routine prescription",
    trueUrgency: "medium",
    category: "routine",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 5,
    phases: ["early", "deep"],
    ignored: { patientSafety: -1, reputation: -1, pagerBacklog: 1, score: -2 },
    handledWell: { patientSafety: 1, reputation: 1, score: 2 },
    delegableTo: ["fy1", "trusted_fy2"],
    riskyDelegateTo: ["locum_no_login"],
    delegationDuration: { fy1: 8, trusted_fy2: 6 },
  },
  {
    id: "mau_discharge_tto_query",
    locationId: "mau",
    message: "Discharge TTO missing inhaler, patient transport booked for 0700",
    revealAtIntel2:
      "Confirmed — just the inhaler missing from the TTO before a 07:00 transport. Administrative but time-bound; sort or delegate before the patient leaves.",
    sender: "MAU nurse",
    source: "pager",
    claimedUrgency: "please sort overnight",
    trueUrgency: "medium",
    category: "routine",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 5,
    phases: ["pre_handover"],
    ignored: {
      patientSafety: -1,
      reputation: -1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -3,
    },
    handledWell: {
      patientSafety: 1,
      reputation: 1,
      handoverQuality: 1,
      score: 3,
    },
    delegableTo: ["fy1", "trusted_fy2", "locum_no_login"],
    riskyDelegateTo: [],
    delegationDuration: { fy1: 12, trusted_fy2: 8, locum_no_login: 18 },
  },
  {
    id: "pharmacy_missing_antibiotic_stop_date",
    locationId: "pharmacy",
    message: "Antibiotic review box blank for patient on day 5 co-amoxiclav",
    revealAtIntel2:
      "Confirmed — day 5 co-amoxiclav with a blank review date. Set a stop/review date per stewardship; not urgent but worth closing off.",
    sender: "On-call pharmacist",
    source: "pager",
    claimedUrgency: "stewardship query",
    trueUrgency: "medium",
    category: "routine",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 4,
    phases: ["early", "pre_handover"],
    ignored: { patientSafety: -1, pagerBacklog: 1, score: -1 },
    handledWell: { patientSafety: 1, reputation: 1, score: 2 },
    delegableTo: ["fy1", "trusted_fy2"],
    riskyDelegateTo: ["locum_no_login"],
    delegationDuration: { fy1: 10, trusted_fy2: 8 },
  },
  {
    id: "resp_neb_frequency",
    locationId: "respiratory",
    message: "Can salbutamol nebs be changed from PRN to regular overnight",
    revealAtIntel2:
      "Confirmed — a wheezy patient who genuinely needs regular rather than PRN salbutamol overnight. A straightforward prescribing change.",
    sender: "Respiratory nurse",
    source: "pager",
    claimedUrgency: "prescribing request",
    trueUrgency: "medium",
    category: "routine",
    encounterId: null,
    timeToDeterioration: 120,
    vague: false,
    regSense: false,
    weight: 5,
    phases: ["early", "deep"],
    ignored: { patientSafety: -1, pagerBacklog: 1, score: -1 },
    handledWell: { patientSafety: 1, reputation: 1, score: 2 },
    delegableTo: ["fy1", "trusted_fy2"],
    riskyDelegateTo: [],
    delegationDuration: { fy1: 8, trusted_fy2: 6 },
  },
  {
    id: "relatives_update_waiting",
    locationId: "elderly",
    message: "Relatives asking for update before they leave, patient stable",
    revealAtIntel2:
      "Confirmed — the patient is stable and the family just want reassurance before leaving. Low clinical priority, but a two-minute call keeps relations good.",
    sender: "Ward nurse",
    source: "pager",
    claimedUrgency: "family waiting",
    trueUrgency: "low",
    category: "routine",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 4,
    phases: ["early"],
    ignored: { reputation: -1, pagerBacklog: 1, score: -1 },
    handledWell: { reputation: 2, focus: -1, stamina: -1, score: 1 },
    delegableTo: ["trusted_fy2"],
    riskyDelegateTo: ["fy1", "locum_no_login"],
    delegationDuration: { trusted_fy2: 15 },
  },
  {
    id: "cannula_for_iv_fluids",
    locationId: "mau",
    message: "Cannula tissued, needs IV fluids overnight",
    revealAtIntel2:
      "Confirmed — a tissued cannula with fluids genuinely due overnight. Needs re-siting; safe to delegate to a competent pair of hands.",
    sender: "MAU nurse",
    source: "pager",
    claimedUrgency: "cannula please",
    trueUrgency: "medium",
    category: "routine",
    encounterId: null,
    timeToDeterioration: 120,
    vague: false,
    regSense: false,
    weight: 5,
    phases: ["early", "deep"],
    ignored: { patientSafety: -1, reputation: -1, pagerBacklog: 1, score: -2 },
    handledWell: {
      patientSafety: 1,
      reputation: 1,
      focus: -1,
      stamina: -1,
      score: 1,
    },
    delegableTo: ["fy1", "trusted_fy2", "locum_no_login"],
    riskyDelegateTo: [],
    delegationDuration: { fy1: 12, trusted_fy2: 8, locum_no_login: 20 },
  },
  {
    id: "routine_vte_risk",
    locationId: "surgical",
    message: "VTE assessment missing for medical outlier on surgical ward",
    revealAtIntel2:
      "Confirmed — the VTE assessment is genuinely outstanding on a medical outlier. Quick to complete and easily delegated.",
    sender: "Surgical ward nurse",
    source: "pager",
    claimedUrgency: "needs completing tonight",
    trueUrgency: "medium",
    category: "routine",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 4,
    phases: ["early", "deep", "pre_handover"],
    ignored: { patientSafety: -1, pagerBacklog: 1, score: -1 },
    handledWell: { patientSafety: 1, reputation: 1, score: 2 },
    delegableTo: ["fy1", "trusted_fy2", "locum_no_login"],
    riskyDelegateTo: [],
    delegationDuration: { fy1: 8, trusted_fy2: 6, locum_no_login: 12 },
  },
  {
    id: "insulin_sliding_scale_review",
    locationId: "mau",
    message: "Variable rate insulin prescription expires at 0400",
    revealAtIntel2:
      "Confirmed — the variable-rate insulin expires at 04:00 and the patient still needs it. Review and re-prescribe before it lapses to avoid a gap.",
    sender: "MAU nurse",
    source: "pager",
    claimedUrgency: "please review",
    trueUrgency: "medium",
    category: "routine",
    encounterId: null,
    timeToDeterioration: 90,
    vague: false,
    regSense: false,
    weight: 6,
    phases: ["deep"],
    ignored: { patientSafety: -2, reputation: -1, pagerBacklog: 1, score: -3 },
    handledWell: {
      patientSafety: 2,
      reputation: 1,
      clinicalConfidence: 1,
      score: 3,
    },
    delegableTo: ["trusted_fy2"],
    riskyDelegateTo: ["fy1", "locum_no_login"],
    delegationDuration: { trusted_fy2: 8 },
  },
  {
    id: "urgent_paracetamol_renewal",
    locationId: "elderly",
    message: "Urgent: paracetamol not prescribed and patient wants it now",
    revealAtIntel2:
      "Confirmed — a simple paracetamol re-prescription flagged 'urgent' that isn't. Prescribe or delegate; don't let the label jump the queue.",
    sender: "Ward nurse",
    source: "pager",
    claimedUrgency: "urgent",
    trueUrgency: "low",
    category: "inappropriate",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 4,
    phases: ["deep"],
    ignored: { reputation: -1, pagerBacklog: 1, inappropriateAvoided: 1 },
    handledWell: { reputation: 1, focus: -1 },
    delegableTo: ["fy1", "trusted_fy2", "locum_no_login"],
    riskyDelegateTo: [],
    delegationDuration: { fy1: 6, trusted_fy2: 5, locum_no_login: 10 },
  },
  {
    id: "sleeping_tablet_request",
    locationId: "surgical",
    message: "Patient asking for zopiclone, never had it before",
    revealAtIntel2:
      "Confirmed — a patient requesting zopiclone they've never had, with no clinical indication overnight. Reasonable to decline and offer non-drug measures.",
    sender: "Surgical ward nurse",
    source: "pager",
    claimedUrgency: "urgent patient request",
    trueUrgency: "low",
    category: "inappropriate",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 4,
    phases: ["deep"],
    ignored: { reputation: -1, pagerBacklog: 1, inappropriateAvoided: 1 },
    handledWell: { reputation: 1, focus: -1 },
    delegableTo: ["fy1", "trusted_fy2"],
    riskyDelegateTo: ["locum_no_login"],
    delegationDuration: { fy1: 8, trusted_fy2: 6 },
  },
  {
    id: "discharge_summary_2019",
    locationId: "mau",
    message:
      "Can you rewrite a 2019 discharge summary because clinic cannot find it",
    sender: "Site admin message",
    source: "system",
    claimedUrgency: "urgent admin",
    trueUrgency: "nonsense",
    category: "inappropriate",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 4,
    phases: ["early", "deep", "pre_handover"],
    ignored: { focus: 1, inappropriateAvoided: 1, score: 2 },
    handledWell: { focus: -2, stamina: -1, score: -2 },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login"],
    delegationDuration: {},
  },
  {
    id: "routine_sick_note",
    locationId: "elderly",
    message: "Relative asking for fit note for patient's son's employer",
    sender: "Ward clerk",
    source: "pager",
    claimedUrgency: "needs doing tonight",
    trueUrgency: "nonsense",
    category: "inappropriate",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 4,
    phases: ["early", "pre_handover"],
    ignored: { focus: 1, inappropriateAvoided: 1, score: 2 },
    handledWell: { focus: -1, stamina: -1, score: -1 },
    delegableTo: ["fy1"],
    riskyDelegateTo: [],
    delegationDuration: { fy1: 12 },
  },
  {
    id: "urgent_fluid_balance_rewrite",
    locationId: "respiratory",
    message: "Urgent: fluid balance chart is messy, can you rewrite totals",
    revealAtIntel2:
      "Confirmed — they want the fluid-chart totals tidied, nothing clinical. Not a doctor job tonight; redirect to nursing.",
    sender: "Ward nurse",
    source: "pager",
    claimedUrgency: "urgent",
    trueUrgency: "low",
    category: "inappropriate",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 4,
    phases: ["deep", "pre_handover"],
    ignored: { focus: 1, inappropriateAvoided: 1, score: 2 },
    handledWell: { focus: -1, stamina: -1, score: -1 },
    delegableTo: ["fy1", "locum_no_login"],
    riskyDelegateTo: [],
    delegationDuration: { fy1: 10, locum_no_login: 14 },
  },
  {
    id: "bed_manager_clinical_priority_form",
    locationId: "mau",
    message:
      "Can you rank all medical outliers by discharge likelihood before 0600",
    revealAtIntel2:
      "Confirmed — a bed-pressure ranking exercise dressed up as urgent. Not a clinical priority overnight; push back or hand it to the bed manager.",
    sender: "Bed manager",
    source: "pager",
    claimedUrgency: "urgent bed pressure",
    trueUrgency: "low",
    category: "inappropriate",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 5,
    phases: ["deep", "pre_handover"],
    ignored: {
      reputation: -1,
      focus: 1,
      chaosSurvived: 1,
      inappropriateAvoided: 1,
      score: 2,
    },
    handledWell: { reputation: 1, focus: -2, stamina: -1, score: -1 },
    delegableTo: ["bed_manager"],
    riskyDelegateTo: ["fy1", "trusted_fy2"],
    delegationDuration: { bed_manager: 7 },
  },
  {
    id: "epr_downtime_results",
    locationId: "mau",
    message:
      "EPR downtime, lab results printing in ED only, nobody knows whose potassium is high",
    revealAtIntel1:
      "Tracked it down — the high potassium is 6.5 on a renal-ward patient, with the result stuck in the ED printer for two hours. Nobody had seen it.",
    revealAtIntel2:
      "Full picture: K 6.5 with ECG changes on a dialysis patient, lost in the EPR downtime. Needs treating now, plus a systematic sweep of all the unlinked results.",
    sender: "Night coordinator",
    source: "system",
    claimedUrgency: "systems issue",
    trueUrgency: "high",
    category: "urgent",
    encounterId: null,
    timeToDeterioration: 45,
    vague: true,
    regSense: true,
    weight: 9,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -3,
      reputation: -2,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 2,
      handoverQuality: -2,
      score: -7,
    },
    handledWell: {
      patientSafety: 3,
      reputation: 2,
      focus: -2,
      stamina: -2,
      clinicalConfidence: 1,
      handoverQuality: 2,
      chaosSurvived: 2,
      score: 7,
    },
    delegableTo: ["trusted_fy2", "bed_manager"],
    riskyDelegateTo: ["fy1", "locum_no_login"],
    delegationDuration: { trusted_fy2: 20, bed_manager: 15 },
  },
  {
    id: "missing_drug_chart",
    locationId: "elderly",
    message:
      "Drug chart missing for bay patient due IV antibiotics and insulin",
    revealAtIntel2:
      "Full picture: without the chart the patient will miss IV antibiotics and insulin doses overnight. Rewrite the critical meds now and report the lost chart.",
    sender: "Ward nurse",
    source: "pager",
    claimedUrgency: "chart missing",
    trueUrgency: "high",
    category: "urgent",
    encounterId: null,
    timeToDeterioration: 60,
    vague: false,
    regSense: false,
    weight: 8,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -3,
      reputation: -1,
      dangerousDelays: 1,
      datix: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -5,
    },
    handledWell: {
      patientSafety: 3,
      reputation: 1,
      focus: -1,
      stamina: -1,
      clinicalConfidence: 1,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 5,
    },
    delegableTo: ["fy1", "trusted_fy2"],
    riskyDelegateTo: ["locum_no_login"],
    delegationDuration: { fy1: 15, trusted_fy2: 10 },
  },
  {
    id: "radiology_ct_pushback",
    locationId: "radiology",
    message:
      "Radiology wants consultant name before scanning drowsy patient with headache",
    revealAtIntel1:
      "Spoke to radiology — they'll scan but want a named consultant. The patient is genuinely drowsy with a new severe headache; the scan is clinically urgent.",
    revealAtIntel2:
      "Full picture: thunderclap headache with a reduced GCS — possible subarachnoid or intracranial bleed. The scan must not be delayed by paperwork; escalate to get it authorised now.",
    sender: "Radiology coordinator",
    source: "pager",
    claimedUrgency: "protocol query",
    trueUrgency: "high",
    category: "urgent",
    encounterId: null,
    timeToDeterioration: 40,
    vague: true,
    regSense: true,
    weight: 8,
    phases: ["early", "deep", "pre_handover"],
    ignored: {
      patientSafety: -3,
      reputation: -2,
      dangerousDelays: 1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -6,
    },
    handledWell: {
      patientSafety: 3,
      reputation: 2,
      focus: -1,
      stamina: -1,
      clinicalConfidence: 1,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 6,
    },
    delegableTo: ["trusted_fy2"],
    riskyDelegateTo: ["fy1", "locum_no_login"],
    delegationDuration: { trusted_fy2: 8 },
  },
  {
    id: "printer_failure_drug_round",
    locationId: "pharmacy",
    message:
      "Ward printer failed, nurses cannot print replacement insulin chart",
    revealAtIntel1:
      "Checked — without the chart the variable-rate insulin can't be continued safely and the next dose is due soon. It's a patient-safety issue, not just IT.",
    revealAtIntel2:
      "Full picture: insulin will be missed across the round if nothing is done. The quick fix is a handwritten interim chart now; flag IT for the systemic problem.",
    sender: "Night coordinator",
    source: "system",
    claimedUrgency: "IT issue",
    trueUrgency: "medium",
    category: "urgent",
    encounterId: null,
    timeToDeterioration: 120,
    vague: false,
    regSense: true,
    weight: 6,
    phases: ["deep", "pre_handover"],
    ignored: {
      patientSafety: -2,
      reputation: -1,
      pagerBacklog: 1,
      handoverQuality: -1,
      score: -3,
    },
    handledWell: {
      patientSafety: 2,
      reputation: 1,
      focus: -1,
      stamina: -1,
      handoverQuality: 1,
      chaosSurvived: 1,
      score: 4,
    },
    delegableTo: ["fy1", "trusted_fy2", "bed_manager"],
    riskyDelegateTo: [],
    delegationDuration: { fy1: 12, trusted_fy2: 8, bed_manager: 10 },
  },
  {
    id: "blood_gas_analyser_broken",
    locationId: "mau",
    message:
      "Blood gas analyser rejecting all samples, ED says use theirs only for resus",
    revealAtIntel1:
      "Looked into it — the only working analyser is in ED resus, so any sick MAU patient needing a gas now means a trip across the hospital.",
    revealAtIntel2:
      "Full picture: gas turnaround is badly delayed for everyone tonight. Plan: triage who genuinely needs a gas, use ED's for the sickest, and escalate the fault.",
    sender: "MAU nurse in charge",
    source: "system",
    claimedUrgency: "equipment issue",
    trueUrgency: "medium",
    category: "urgent",
    encounterId: null,
    timeToDeterioration: 90,
    vague: false,
    regSense: true,
    weight: 7,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -2,
      reputation: -1,
      pagerBacklog: 2,
      handoverQuality: -1,
      score: -4,
    },
    handledWell: {
      patientSafety: 2,
      reputation: 1,
      focus: -1,
      stamina: -1,
      handoverQuality: 1,
      chaosSurvived: 2,
      score: 5,
    },
    delegableTo: ["trusted_fy2", "bed_manager"],
    riskyDelegateTo: ["fy1"],
    delegationDuration: { trusted_fy2: 15, bed_manager: 10 },
  },
  {
    id: "no_cannulas_hospital",
    locationId: "pharmacy",
    message:
      "No green cannulas left on MAU, stores locked, three IV starts pending",
    revealAtIntel1:
      "Checked — three patients need IV access for antibiotics and fluids and there's genuinely no kit on the ward; stores are locked overnight.",
    revealAtIntel2:
      "Full picture: time-critical IV antibiotics are at risk. Plan: borrow from a neighbouring ward now, get site to open stores, and don't let the sepsis dose slip.",
    sender: "MAU nurse in charge",
    source: "system",
    claimedUrgency: "stock issue",
    trueUrgency: "medium",
    category: "urgent",
    encounterId: null,
    timeToDeterioration: 120,
    vague: false,
    regSense: true,
    weight: 6,
    phases: ["early", "deep", "pre_handover"],
    ignored: {
      patientSafety: -2,
      reputation: -1,
      pagerBacklog: 2,
      handoverQuality: -1,
      score: -4,
    },
    handledWell: {
      patientSafety: 2,
      reputation: 1,
      focus: -1,
      stamina: -1,
      handoverQuality: 1,
      chaosSurvived: 2,
      score: 5,
    },
    delegableTo: ["fy1", "trusted_fy2", "bed_manager"],
    riskyDelegateTo: [],
    delegationDuration: { fy1: 15, trusted_fy2: 10, bed_manager: 8 },
  },
  {
    id: "estates_ceiling_leak",
    locationId: "estates",
    message:
      "Ceiling leak over corridor outside side room, patient notes getting damp",
    revealAtIntel1:
      "Had a look — the leak is over a corridor, not a patient. The main risk is wet notes and a slip hazard; no immediate clinical danger.",
    revealAtIntel2:
      "Full picture: genuinely an estates/facilities job. Move the notes and trolley, flag the slip risk, and hand it to site — not a medical priority.",
    sender: "Site practitioner",
    source: "pager",
    claimedUrgency: "estates aware, need clinical decision",
    trueUrgency: "low",
    category: "urgent",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: true,
    weight: 5,
    phases: ["deep"],
    ignored: { patientSafety: -1, reputation: -1, pagerBacklog: 1, score: -2 },
    handledWell: {
      patientSafety: 1,
      reputation: 1,
      focus: -1,
      chaosSurvived: 1,
      score: 2,
    },
    delegableTo: ["bed_manager"],
    riskyDelegateTo: ["fy1"],
    delegationDuration: { bed_manager: 7 },
  },
  {
    id: "mess_fridge_alarm",
    locationId: "mess",
    message: "Mess fridge alarm going off, sandwiches at risk",
    sender: "Unknown bleep",
    source: "pager",
    claimedUrgency: "urgent facilities issue",
    trueUrgency: "nonsense",
    category: "absurd",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 4,
    phases: ["deep"],
    ignored: { focus: 1, chaosSurvived: 1, inappropriateAvoided: 1, score: 2 },
    handledWell: { focus: -1, stamina: -1, chaosSurvived: 1 },
    delegableTo: ["bed_manager"],
    riskyDelegateTo: ["fy1", "trusted_fy2"],
    delegationDuration: { bed_manager: 7 },
  },
  {
    id: "corridor_pigeon",
    locationId: "corridor",
    message:
      "There is a pigeon outside AMU bay 3 and infection control are not answering",
    sender: "Porter",
    source: "pager",
    claimedUrgency: "urgent infection control",
    trueUrgency: "nonsense",
    category: "absurd",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 4,
    phases: ["early", "deep"],
    ignored: { focus: 1, chaosSurvived: 1, inappropriateAvoided: 1, score: 2 },
    handledWell: { focus: -1, chaosSurvived: 1 },
    delegableTo: ["bed_manager"],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login"],
    delegationDuration: { bed_manager: 7 },
  },
  {
    id: "lifts_duck_family",
    locationId: "lifts",
    message: "Lift B stuck open with a duck and three ducklings inside",
    sender: "Security",
    source: "pager",
    claimedUrgency: "major incident pending",
    trueUrgency: "nonsense",
    category: "absurd",
    encounterId: null,
    timeToDeterioration: 180,
    vague: false,
    regSense: false,
    weight: 4,
    phases: ["deep", "pre_handover"],
    ignored: { focus: 1, chaosSurvived: 1, inappropriateAvoided: 1, score: 2 },
    handledWell: { focus: -1, chaosSurvived: 1 },
    delegableTo: ["bed_manager"],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login"],
    delegationDuration: { bed_manager: 7 },
  },
];

export const bleepPackTasks: TaskTemplate[] = rawBleepPack.map(
  ({ encounterId, ...task }) => {
    const mappedEncounterId = encounterId
      ? encounterMap[encounterId]
      : undefined;
    return mappedEncounterId
      ? { ...task, encounterId: mappedEncounterId }
      : task;
  },
);
