import type { Encounter, Location, PagerEvent, TaskTemplate } from "./types";
import { bleepPackTasks } from "./bleepPack";
import { regSensePackTasks } from "./regSensePack";
import { scenarioPackEncounters, scenarioPackTasks } from "./scenarioPack";

export const SHIFT_LENGTH = 720;

export const locations: Location[] = [
  { id: "ed_resus", name: "ED Resus", flavour: "Monitors sing in discordant thirds. Everyone is busy, but everyone knows exactly where the difficult airway trolley is.", links: ["mau", "corridor", "icu"], timeCost: 5, risk: "volatile", categories: ["emergency", "urgent"], quirk: "Resus phone rings just as your bleep goes off." },
  { id: "mau", name: "Medical Assessment Unit", flavour: "The board is full, the chairs are full, and the phrase 'just needs a medics review' hangs in the air.", links: ["ed_resus", "corridor", "respiratory", "cardiology", "elderly"], timeCost: 4, risk: "high", categories: ["urgent", "ambiguous", "routine"], quirk: "Bed pressure adds a minute to most decisions." },
  { id: "respiratory", name: "Respiratory Ward", flavour: "Nebulisers hiss beside an ABG machine displaying a message nobody wanted to read.", links: ["mau", "corridor", "lifts"], timeCost: 4, risk: "high", categories: ["emergency", "urgent", "ambiguous"], quirk: "The blood gas analyser is intermittently out of cartridges." },
  { id: "cardiology", name: "Cardiology Ward", flavour: "A telemetry printer clatters like it is personally offended by potassium.", links: ["mau", "corridor", "lifts"], timeCost: 4, risk: "high", categories: ["emergency", "urgent", "ambiguous"], quirk: "Every ECG is 'just to cast your eye over'." },
  { id: "elderly", name: "Care of the Elderly", flavour: "Bay lights are low, delirium is high, and one patient is determined to find a bus stop.", links: ["mau", "corridor", "surgical"], timeCost: 4, risk: "moderate", categories: ["urgent", "ambiguous", "routine"], quirk: "Collateral history unlocks better decisions but costs time." },
  { id: "surgical", name: "Surgical Ward", flavour: "The referral simply says 'medical optimisation please' and somehow includes no observations.", links: ["elderly", "corridor", "pharmacy"], timeCost: 4, risk: "moderate", categories: ["urgent", "routine", "inappropriate"], quirk: "The drug chart may be missing, present, or metaphysical." },
  { id: "icu", name: "ICU", flavour: "A bright, competent island. You feel both reassured and gently judged.", links: ["ed_resus", "corridor", "lifts"], timeCost: 5, risk: "high", categories: ["emergency", "urgent"], quirk: "Good referrals are rewarded; vague referrals are not." },
  { id: "radiology", name: "Radiology", flavour: "The CT scanner is working, but only in the philosophical sense.", links: ["corridor", "lifts"], timeCost: 5, risk: "moderate", categories: ["urgent", "routine"], quirk: "Clinical justification required. Also patience." },
  { id: "pharmacy", name: "Pharmacy Hatch", flavour: "Closed, obviously. A laminated sign explains how to summon help by ritual phone call.", links: ["surgical", "corridor"], timeCost: 3, risk: "low", categories: ["routine", "inappropriate"], quirk: "On-call pharmacy can save you, slowly." },
  { id: "mess", name: "Doctors' Mess", flavour: "A sanctuary with two chairs, one working microwave, and a kettle with a handwritten warning.", links: ["corridor", "lifts"], timeCost: 3, risk: "low", categories: ["routine", "absurd"], quirk: "Restores stamina, unless the kettle has given up." },
  { id: "corridor", name: "Main Corridor", flavour: "A long institutional artery of strip lighting, wheelie bins, and unclear signage.", links: ["ed_resus", "mau", "respiratory", "cardiology", "elderly", "surgical", "icu", "radiology", "pharmacy", "mess", "lifts", "estates"], timeCost: 3, risk: "moderate", categories: ["ambiguous", "absurd", "routine"], quirk: "A leak intermittently closes the quickest route." },
  { id: "lifts", name: "Lift Lobby", flavour: "Three lifts. One works. It is going the other way forever.", links: ["corridor", "respiratory", "cardiology", "icu", "radiology", "mess"], timeCost: 6, risk: "moderate", categories: ["routine", "absurd"], quirk: "Broken lift delays are common; porter knowledge helps." },
  { id: "estates", name: "Estates Trouble Zone", flavour: "A service corridor where the hospital reveals its deeper architectural opinions.", links: ["corridor"], timeCost: 5, risk: "moderate", categories: ["absurd", "inappropriate", "routine"], quirk: "Swipe access has feelings." },
];

const clinicalChoices = {
  good: (label: string, detail: string, feedback: string) => ({
    id: "best",
    label,
    detail,
    feedback,
    resolves: true,
    consequence: { time: 14, stamina: -7, focus: -5, reputation: 4, patientSafety: 8, clinicalConfidence: 6, score: 160, handoverQuality: 5, emergenciesHandled: 1, patientsStabilised: 1 },
  }),
  partial: (label: string, detail: string, feedback: string) => ({
    id: "partial",
    label,
    detail,
    feedback,
    resolves: true,
    consequence: { time: 18, stamina: -9, focus: -8, reputation: 1, patientSafety: -3, clinicalConfidence: 2, score: 60, handoverQuality: 1 },
  }),
  unsafe: (label: string, detail: string, feedback: string) => ({
    id: "unsafe",
    label,
    detail,
    feedback,
    unsafe: true,
    resolves: true,
    consequence: { time: 10, stamina: -6, focus: -7, reputation: -6, patientSafety: -18, score: -120, dangerousDelays: 1, datix: 1, consultantEscalations: 1 },
  }),
};

export const encounters: Encounter[] = [
  {
    id: "sepsis_hypotension",
    title: "Hypotensive Sepsis",
    locationId: "mau",
    category: "emergency",
    vignette: "A 72-year-old admitted with rigors is now grey, confused, and trying to pull off the sats probe.",
    observations: "T 39.1, HR 124, BP 78/42, RR 30, SpO2 92% on 4L, GCS 14 from baseline 15.",
    examination: "Cool peripheries, prolonged cap refill, crackles right base, mild suprapubic tenderness.",
    investigations: ["VBG lactate 5.2", "WCC 21", "Creatinine 198 from 86", "CXR pending", "Urine dip nitrites positive"],
    choices: [
      clinicalChoices.good("ABCDE, cultures, broad-spectrum antibiotics, fluid bolus, senior/ICU early", "Treat septic shock, reassess response, document ceilings of care and escalation.", "You stabilise the patient enough for ICU review. The nurse gives the tiny nod of respect."),
      clinicalChoices.partial("Give antibiotics and request CXR before reassessing", "You treat infection but delay circulatory resuscitation and escalation.", "Some good work, but the hypotension was the immediate threat."),
      clinicalChoices.unsafe("Ask for repeat observations in 30 minutes", "The patient looks unwell but the unit is busy.", "The patient deteriorates. This was septic shock until proved otherwise."),
    ],
  },
  {
    id: "acute_asthma",
    title: "Acute Severe Asthma",
    locationId: "ed_resus",
    category: "emergency",
    vignette: "A 26-year-old with asthma is speaking in single words and looks exhausted.",
    observations: "HR 138, RR 34, SpO2 90% air, PEFR 32% best, silent-ish chest.",
    examination: "Accessory muscle use, poor air entry, no urticaria, too tired to complete sentences.",
    investigations: ["VBG pH 7.31", "CO2 6.1", "K 3.3", "CXR no pneumothorax"],
    choices: [
      clinicalChoices.good("High-flow oxygen, back-to-back nebs, steroids, IV magnesium, anaesthetics/ICU", "Recognise life-threatening features and prepare for ventilatory failure.", "The escalation is timely. Nobody says 'just asthma' again."),
      clinicalChoices.partial("Nebulisers and steroids, review after the next bleep", "Initial treatment is right but review and escalation are too casual.", "They improve a little, but you nearly miss exhaustion."),
      clinicalChoices.unsafe("Controlled oxygen because you are worried about CO2 retention", "Apply COPD logic to asthma.", "This is the wrong physiology. The sats fall and resus gets very loud."),
    ],
  },
  {
    id: "copd_hypercapnia",
    title: "COPD With Hypercapnia",
    locationId: "respiratory",
    category: "urgent",
    vignette: "A 68-year-old with severe COPD is drowsy after oxygen was increased for sats of 86%.",
    observations: "HR 112, RR 26, SpO2 99% on 15L, drowsy but rousable.",
    examination: "Wheeze, poor air entry, flapping tremor, no focal neurology.",
    investigations: ["ABG pH 7.24", "pCO2 10.2", "pO2 18.6", "HCO3 34", "CXR hyperinflation"],
    choices: [
      clinicalChoices.good("Titrate oxygen to target sats, bronchodilators, steroids/antibiotics, start NIV pathway", "Correct oxygen strategy and treat acidotic hypercapnic respiratory failure.", "Respiratory nurse finds the NIV mask and you earn a quiet victory."),
      clinicalChoices.partial("Start treatment but leave oxygen at 15L until respiratory arrives", "You treat the exacerbation but worsen hypercapnia.", "The patient remains drowsy and needs more rescue work."),
      clinicalChoices.unsafe("Give sedative for agitation before ABG review", "Treat agitation before recognising ventilatory failure.", "The CO2 climbs. This is a Datix-shaped decision."),
    ],
  },
  {
    id: "nstemi",
    title: "NSTEMI With Risk Stratification",
    locationId: "cardiology",
    category: "urgent",
    vignette: "A 59-year-old with diabetes has central chest pressure and dynamic ST depression.",
    observations: "HR 94, BP 156/88, SpO2 96%, pain 7/10.",
    examination: "No murmur, clear chest, no heart failure, equal pulses.",
    investigations: ["Troponin 420 then 930", "ECG lateral ST depression", "Hb 118", "Creatinine 92"],
    choices: [
      clinicalChoices.good("Treat ACS, assess bleeding risk, dual antiplatelet/anticoagulation per protocol, discuss cardiology", "Risk stratify, treat pain, and arrange early invasive strategy.", "Cardiology accepts with only moderate ritual resistance."),
      clinicalChoices.partial("Repeat troponin in six hours before treating", "You seek certainty but ignore dynamic ischaemia.", "The diagnosis was already clinically strong."),
      clinicalChoices.unsafe("Reassure because the first ECG has no ST elevation", "No STEMI does not mean no problem.", "The pain worsens and your reputation takes the lift down."),
    ],
  },
  {
    id: "broad_complex_tachy",
    title: "Broad Complex Tachycardia",
    locationId: "cardiology",
    category: "emergency",
    vignette: "Telemetry shows a regular broad complex tachycardia in a pale, sweaty 81-year-old.",
    observations: "HR 178, BP 82 systolic, clammy, chest discomfort.",
    examination: "No obvious reversible drug trigger on first look; peripheral shutdown.",
    investigations: ["ECG regular broad complex tachycardia", "K 4.5", "Mg pending"],
    choices: [
      clinicalChoices.good("Treat as unstable VT: call help, synchronised DC cardioversion, ALS approach", "Instability decides urgency; do not admire the ECG for too long.", "The rhythm breaks. Someone writes the time on a paper towel."),
      clinicalChoices.partial("Amiodarone infusion while arranging senior review", "Drug therapy alone is too slow for unstable tachycardia.", "You are rescued by escalation, but it was getting close."),
      clinicalChoices.unsafe("Try carotid sinus massage and wait", "Assume SVT despite broad complexes and shock.", "The blood pressure disappears from the machine and from your evening."),
    ],
  },
  {
    id: "delirium",
    title: "Delirium And Wandering",
    locationId: "elderly",
    category: "ambiguous",
    vignette: "An 86-year-old is shouting that she needs the number 42 bus and is trying to leave the ward.",
    observations: "T 37.9, HR 106, BP 104/62, RR 22, SpO2 94%, new confusion.",
    examination: "Dry mucosa, suprapubic tenderness, bruised hip after a reported slide from chair.",
    investigations: ["Urine dip positive nitrites", "Na 129", "CRP 116", "Hip X-ray pending"],
    choices: [
      clinicalChoices.good("Assess delirium triggers, pain, infection, electrolytes, capacity, falls injury, de-escalate", "Treat cause and risk, not just behaviour.", "The ward feels safer and nobody has to wrestle with a clipboard."),
      clinicalChoices.partial("Prescribe low-dose antipsychotic and ask for urine culture", "May be needed for severe distress, but you under-address causes.", "The immediate noise drops, the underlying problem remains."),
      clinicalChoices.unsafe("Discharge because she is mobile and wants to go", "Ignore capacity, delirium, infection, and injury risk.", "This becomes the sort of story told at governance meetings."),
    ],
  },
  {
    id: "ugi_bleed",
    title: "Upper GI Bleed",
    locationId: "surgical",
    category: "emergency",
    vignette: "A patient admitted under surgeons for abdominal pain has had a large melaena and is dizzy.",
    observations: "HR 128, BP 86/50, RR 24, SpO2 96%, pale.",
    examination: "Epigastric tenderness, cool peripheries, no stigmata recorded because nobody can find the notes.",
    investigations: ["Hb 72 from 119", "Urea 18", "INR 1.8 on warfarin", "Group and save not yet sent"],
    choices: [
      clinicalChoices.good("Resuscitate, two large cannulas, bloods/crossmatch, reverse anticoagulation, urgent endoscopy/ITU discussion", "Treat haemorrhagic shock and coordinate definitive care.", "The right people arrive. The missing drug chart reappears, smugly."),
      clinicalChoices.partial("Start PPI and request routine endoscopy", "You treat the ulcer idea but not the shock.", "The physiology remains insulted."),
      clinicalChoices.unsafe("Prescribe oral iron and review morning Hb", "This is not anaemia clinic.", "The patient collapses before morning."),
    ],
  },
  {
    id: "dka",
    title: "DKA At 03:10",
    locationId: "mau",
    category: "urgent",
    vignette: "A 31-year-old with type 1 diabetes has vomiting, abdominal pain, and Kussmaul breathing.",
    observations: "HR 122, BP 98/58, RR 30, ketotic breath, dry.",
    examination: "No peritonism, looks dehydrated, insulin pump disconnected.",
    investigations: ["Glucose 28", "Ketones 6.5", "pH 7.18", "K 5.7", "Bicarb 9"],
    choices: [
      clinicalChoices.good("Start DKA protocol: fluids, fixed-rate insulin, potassium strategy, trigger search, close monitoring", "Protocolised care, but with registrar-level attention to potassium and cause.", "The SHO visibly relaxes when you explain the potassium plan."),
      clinicalChoices.partial("Give stat insulin and antiemetic, repeat gas later", "A single dose is not DKA management.", "The numbers improve briefly, then the problem returns."),
      clinicalChoices.unsafe("Delay insulin because potassium is high", "High serum K in DKA does not mean total body potassium is safe.", "The acidosis worsens and the nurse asks the question in a tone."),
    ],
  },
  {
    id: "aki_hyperkalaemia",
    title: "AKI With Hyperkalaemia",
    locationId: "elderly",
    category: "emergency",
    vignette: "Routine bloods show potassium 7.1 in a patient on ramipril, spironolactone, and trimethoprim.",
    observations: "HR 48, BP 102/58, SpO2 97%, slightly nauseated.",
    examination: "Mild dehydration, no pulmonary oedema, bradycardic but alert.",
    investigations: ["ECG tall tented T waves", "Creatinine 284 from 92", "K 7.1, repeat 7.0", "Bicarb 18"],
    choices: [
      clinicalChoices.good("IV calcium, shift K, stop culprits, fluids if appropriate, monitor ECG, renal advice", "Stabilise myocardium first, then lower potassium and address AKI.", "The ECG becomes less terrifying. Renal answers on the second call."),
      clinicalChoices.partial("Give insulin/dextrose and repeat U&Es", "You lower potassium but miss immediate membrane stabilisation.", "Better, but the ECG was asking politely to be taken seriously."),
      clinicalChoices.unsafe("Treat as haemolysed sample and leave for day team", "Repeat confirms it, ECG confirms it, night confirms consequences.", "The monitor alarm makes the teaching point."),
    ],
  },
  {
    id: "stroke_mimic",
    title: "Stroke Mimic Or Thrombolysis Dilemma",
    locationId: "ed_resus",
    category: "urgent",
    vignette: "A 74-year-old has aphasia and right arm weakness. Onset may be 90 minutes ago, or 'sometime after tea'.",
    observations: "HR 88 AF, BP 184/96, glucose 2.9, SpO2 97%.",
    examination: "Expressive dysphasia, right pronator drift, no seizure witnessed.",
    investigations: ["CT head no bleed", "Glucose low", "INR 1.1", "Collateral incomplete"],
    choices: [
      clinicalChoices.good("Correct hypoglycaemia, establish last-known-well, NIHSS, stroke call, discuss thrombolysis/thrombectomy eligibility", "You separate mimic correction from true stroke pathway.", "The deficit partly improves after glucose, and stroke team stays engaged."),
      clinicalChoices.partial("Send for CT and wait for formal report before any bedside correction", "Imaging matters, but glucose was immediately fixable.", "You lose time on a reversible contributor."),
      clinicalChoices.unsafe("Thrombolyse immediately without glucose or timing clarification", "Urgency cannot skip exclusions.", "The room becomes very quiet for the wrong reason."),
    ],
  },
  {
    id: "pe_risk",
    title: "PE Risk Stratification",
    locationId: "respiratory",
    category: "urgent",
    vignette: "A post-op patient is pleuritic, tachycardic, and asking whether anxiety can cause oxygen to be 89%.",
    observations: "HR 126, BP 118/74, RR 28, SpO2 89% air, afebrile.",
    examination: "Clear chest, swollen left calf, no wheeze, no haemoptysis.",
    investigations: ["ECG sinus tachycardia", "CXR clear", "D-dimer unhelpful post-op", "Creatinine 76"],
    choices: [
      clinicalChoices.good("Assess PE probability, oxygen, anticoagulate if safe, CTPA request with clear justification", "You use probability and physiology, not a reflex D-dimer.", "Radiology says yes without making you read the entire Wells score aloud."),
      clinicalChoices.partial("Request D-dimer and await result", "The context makes the test low value.", "It comes back positive, achieving very little except lost time."),
      clinicalChoices.unsafe("Reassure as panic attack after normal CXR", "Normal CXR does not rule out PE.", "The patient deteriorates on the ward."),
    ],
  },
  {
    id: "end_of_life",
    title: "Escalation And End-Of-Life Decision",
    locationId: "elderly",
    category: "urgent",
    vignette: "A frail 91-year-old with advanced heart failure and pneumonia is deteriorating. Family are on speakerphone.",
    observations: "HR 118, BP 88/52, RR 32, SpO2 88% on 15L, drowsy.",
    examination: "Cachectic, widespread crackles, oedema, pressure damage, severe baseline dependency.",
    investigations: ["CXR bilateral consolidation", "CRP 240", "Creatinine 210", "Previous clinic letter suggests limited reversibility"],
    choices: [
      clinicalChoices.good("Assess reversibility, capacity/best interests, discuss ceilings, symptom control, document DNACPR/TEP clearly", "You avoid both therapeutic nihilism and burdensome escalation.", "It is hard, humane work. The ward has a clear plan."),
      clinicalChoices.partial("Continue antibiotics and fluids without escalation decision", "Treatment continues but uncertainty is handed to everyone else.", "The night gets longer because the plan is incomplete."),
      clinicalChoices.unsafe("Call arrest team for CPR if they deteriorate without discussion", "Escalation without benefit can be harmful.", "The family and team are left with avoidable distress."),
    ],
  },
  {
    id: "icu_referral",
    title: "ICU Referral At The Door",
    locationId: "icu",
    category: "urgent",
    vignette: "You arrive on ICU with a septic patient in mind. The registrar asks for the story, the trajectory, and what you are actually asking for.",
    observations: "Current patient: HR 122, BP 92/48 after 1L crystalloid, lactate 4.1 from 5.2, oxygen 6L, urine output poor.",
    examination: "Warm peripheries after fluid, still confused, likely pneumonia source, no clear ceiling documented yet.",
    investigations: ["CXR right lower zone consolidation", "Creatinine rising", "Blood cultures sent", "Antibiotics in", "No TEP form"],
    choices: [
      {
        id: "best",
        label: "Present a concise referral: diagnosis, physiology, response, ceiling, and specific ask",
        detail: "You ask for ICU review for vasopressors/HDU-level monitoring while clarifying escalation with family/consultant.",
        feedback: "The ICU registrar accepts the referral and gives useful advice rather than a sigh.",
        resolves: true,
        unlockAlly: "ICU registrar",
        consequence: { time: 10, stamina: -4, focus: -4, reputation: 5, patientSafety: 5, score: 95, handoverQuality: 4, clinicalConfidence: 4 },
      },
      {
        id: "partial",
        label: "Say 'they are sick, can you come and see them?'",
        detail: "True, but thin. ICU has to reconstruct the clinical question.",
        feedback: "They come, but you lose time rebuilding the referral from scratch.",
        resolves: true,
        consequence: { time: 16, stamina: -5, focus: -5, reputation: -1, patientSafety: 1, score: 20 },
      },
      {
        id: "unsafe",
        label: "Avoid calling because the BP improved once",
        detail: "You interpret transient improvement as stability.",
        feedback: "The patient deteriorates later with a much less controlled referral.",
        unsafe: true,
        resolves: true,
        consequence: { time: 6, focus: -5, reputation: -5, patientSafety: -12, score: -80, dangerousDelays: 1 },
      },
    ],
  },
  {
    id: "radiology_gatekeeping",
    title: "Radiology Gatekeeping",
    locationId: "radiology",
    category: "routine",
    vignette: "You reach radiology to negotiate a CTPA. The request says 'SOB ?PE'. The radiographer has already hovered over reject.",
    observations: "Patient is tachycardic, hypoxic, post-op, with unilateral calf swelling and no alternative on CXR.",
    examination: "Clear chest, no wheeze, calf asymmetry. Bleeding risk is low enough for treatment dose anticoagulation.",
    investigations: ["ECG sinus tachycardia", "CXR clear", "Creatinine normal", "D-dimer not useful in context"],
    choices: [
      {
        id: "best",
        label: "Rewrite the request with pre-test probability, renal function, anticoagulation plan, and urgency",
        detail: "You make the clinical question impossible to miss.",
        feedback: "The scan is accepted. Radiology rewards a request that contains medicine.",
        resolves: true,
        unlockAlly: "Radiographer who trusts good referrals",
        consequence: { time: 8, focus: -3, reputation: 4, patientSafety: 3, score: 70, handoverQuality: 2 },
      },
      {
        id: "partial",
        label: "Phone and say the consultant wants it",
        detail: "Sometimes effective, rarely beautiful.",
        feedback: "It works after friction, but trust capital is spent.",
        resolves: true,
        consequence: { time: 13, stamina: -3, reputation: -1, patientSafety: 1, score: 15 },
      },
      {
        id: "unsafe",
        label: "Abandon imaging because the first request was rejected",
        detail: "A rejected form is not a changed probability.",
        feedback: "The diagnostic delay follows you into handover.",
        unsafe: true,
        resolves: true,
        consequence: { time: 4, patientSafety: -9, reputation: -3, score: -55, dangerousDelays: 1 },
      },
    ],
  },
  {
    id: "pharmacy_hatch",
    title: "On-Call Pharmacy Puzzle",
    locationId: "pharmacy",
    category: "routine",
    vignette: "The pharmacy hatch is closed. A patient needs time-critical Parkinson's medication and the ward cannot find the supply.",
    observations: "No acute observations issue yet, but the missed-dose clock is becoming clinically relevant.",
    examination: "The drug chart exists in two photocopied fragments and a rumour.",
    investigations: ["Medicines reconciliation incomplete", "Previous discharge summary lists co-careldopa", "Controlled access cupboard locked"],
    choices: [
      {
        id: "best",
        label: "Call on-call pharmacy with exact drug, dose, timing, indication, and ward stock checks",
        detail: "You make it easy for pharmacy to solve the right problem.",
        feedback: "The pharmacist appears by phone like a benevolent protocol.",
        resolves: true,
        unlockAlly: "Pharmacist on call",
        consequence: { time: 9, focus: -3, reputation: 4, patientSafety: 3, score: 65, chaosSurvived: 1 },
      },
      {
        id: "partial",
        label: "Ask the FY1 to keep looking while you move on",
        detail: "Delegation helps but lacks a plan.",
        feedback: "The dose is found late and everyone is slightly cross.",
        resolves: true,
        consequence: { time: 5, reputation: -1, patientSafety: -2, score: 5 },
      },
      {
        id: "unsafe",
        label: "Leave it until morning because it is not an emergency drug",
        detail: "Time-critical medicines are not optional flavour text.",
        feedback: "The patient stiffens and the ward has an avoidable problem.",
        unsafe: true,
        resolves: true,
        consequence: { time: 3, patientSafety: -8, reputation: -4, score: -50, datix: 1 },
      },
    ],
  },
  {
    id: "mess_break_decision",
    title: "Doctors' Mess: Recovery Or Trap",
    locationId: "mess",
    category: "absurd",
    vignette: "You enter the mess. There is one edible biscuit, the kettle is questionable, and the sofa has the posture of a legal warning.",
    observations: "You have active bleeps, falling focus, and the dangerous belief that nine minutes will fix everything.",
    examination: "Microwave smells faintly of fish. Someone has written 'please clean up' on a paper towel.",
    investigations: ["Coffee available", "Snack available", "Pager still audible", "No consultant visible"],
    choices: [
      {
        id: "best",
        label: "Take a short deliberate reset and review the bleep queue before leaving",
        detail: "A controlled pause improves cognition without pretending the hospital stopped.",
        feedback: "You return with enough focus to make fewer heroic errors.",
        resolves: true,
        consequence: { time: 7, stamina: 12, focus: 10, caffeine: 10, breaksTaken: 1, score: 45 },
      },
      {
        id: "partial",
        label: "Drink coffee while scrolling the list with one eye",
        detail: "Better than nothing, but not exactly rest.",
        feedback: "The caffeine helps; the existential renewal does not arrive.",
        resolves: true,
        consequence: { time: 4, stamina: 4, focus: 5, caffeine: 14, score: 10 },
      },
      {
        id: "unsafe",
        label: "Sit down properly and ignore the bleep for a bit",
        detail: "A tempting option. The game knows.",
        feedback: "A serious bleep matures quietly in the background.",
        unsafe: true,
        resolves: true,
        consequence: { time: 14, stamina: 8, focus: 4, patientSafety: -8, pagerBacklog: 1, score: -40, dangerousDelays: 1 },
      },
    ],
  },
  {
    id: "corridor_bird",
    title: "Main Corridor Systems Failure",
    locationId: "corridor",
    category: "absurd",
    vignette: "The main corridor contains a wet floor sign, a queue of beds, and a winged administrative incident heading towards cardiology.",
    observations: "No patients are immediately harmed, but flow through the hospital is slowing and everyone is asking you why.",
    examination: "One ceiling tile is dripping. The bird appears clinically stable.",
    investigations: ["Estates voicemail full", "Porter nearby", "Bed manager pacing", "Cardiology doors open"],
    choices: [
      {
        id: "best",
        label: "Coordinate porter, estates, and nurse-in-charge; keep clinical route open",
        detail: "You do not personally chase the bird, but you stop the hospital flow from clotting.",
        feedback: "The corridor becomes passable. The bird is contained without needing a medical clerking.",
        resolves: true,
        unlockAlly: "Porter who knows shortcuts",
        consequence: { time: 8, stamina: -3, reputation: 4, score: 60, chaosSurvived: 3 },
      },
      {
        id: "partial",
        label: "Step around it and hope estates appear",
        detail: "A classic NHS holding pattern.",
        feedback: "Nothing burns down, but the delay spreads.",
        resolves: true,
        consequence: { time: 5, focus: -3, reputation: -1, chaosSurvived: 1 },
      },
      {
        id: "unsafe",
        label: "Personally pursue the bird down the corridor",
        detail: "Technically decisive, clinically questionable.",
        feedback: "You gain a story and lose control of the bleep queue.",
        unsafe: true,
        resolves: true,
        consequence: { time: 12, stamina: -8, focus: -4, pagerBacklog: 1, score: -20, chaosSurvived: 2 },
      },
    ],
  },
  {
    id: "lift_failure",
    title: "Lift Lobby Delay",
    locationId: "lifts",
    category: "routine",
    vignette: "The lift doors open to reveal a bed, a porter, two relatives, and absolutely no space for you.",
    observations: "Your urgent review is upstairs. The lift display has committed to the basement.",
    examination: "Stairwell access requires a swipe card that is having a private crisis.",
    investigations: ["One lift out of service", "Porter knows a service route", "Your sats are fine but patience is not"],
    choices: [
      {
        id: "best",
        label: "Use the service stairs with porter help and update the ward ETA",
        detail: "You solve route and communication together.",
        feedback: "You arrive faster and the ward stops re-bleeping every two minutes.",
        resolves: true,
        unlockAlly: "Porter who knows shortcuts",
        consequence: { time: 5, stamina: -4, reputation: 3, score: 45, chaosSurvived: 1 },
      },
      {
        id: "partial",
        label: "Wait for the lift while answering bleeps",
        detail: "Efficient-looking stasis.",
        feedback: "You clear admin but lose clinical time.",
        resolves: true,
        consequence: { time: 10, focus: -4, reputation: 1, score: 5 },
      },
      {
        id: "unsafe",
        label: "Say you are on your way and do not update anyone",
        detail: "The ward assumes imminent arrival. Physics disagrees.",
        feedback: "The patient is sicker when you arrive.",
        unsafe: true,
        resolves: true,
        consequence: { time: 9, patientSafety: -6, reputation: -4, score: -35 },
      },
    ],
  },
  {
    id: "estates_leak",
    title: "Estates Trouble Zone",
    locationId: "estates",
    category: "absurd",
    vignette: "A ceiling leak has reached the clean utility. The ward asks whether water near electrics is a medical problem.",
    observations: "No one is acutely unwell from the leak yet, but the ward is losing access to kit.",
    examination: "A bin is catching water with surprising dignity. The socket nearby is less reassuring.",
    investigations: ["No dry dressing trolley", "Estates bleep unanswered", "Site practitioner reachable", "Clean utility partially closed"],
    choices: [
      {
        id: "best",
        label: "Escalate to site, move essential stock, and mark the area unsafe",
        detail: "You protect patient care without pretending to be estates.",
        feedback: "The ward keeps functioning and nobody tests mains electricity with optimism.",
        resolves: true,
        consequence: { time: 7, stamina: -3, reputation: 4, patientSafety: 2, score: 55, chaosSurvived: 2 },
      },
      {
        id: "partial",
        label: "Put in another estates call and carry on",
        detail: "Reasonable, but a bit too passive for the risk.",
        feedback: "The problem remains contained, mostly because the nurse is excellent.",
        resolves: true,
        consequence: { time: 4, reputation: 1, patientSafety: -1, chaosSurvived: 1 },
      },
      {
        id: "unsafe",
        label: "Ignore it because nobody is currently peri-arrest",
        detail: "Not all safety problems announce themselves in sinus tachycardia.",
        feedback: "The ward loses access to essential kit at exactly the wrong moment.",
        unsafe: true,
        resolves: true,
        consequence: { time: 2, patientSafety: -7, reputation: -4, score: -40 },
      },
    ],
  },
  {
    id: "neutropenic_sepsis",
    title: "Neutropenic Sepsis",
    locationId: "mau",
    category: "emergency",
    vignette: "A 54-year-old on chemotherapy has rigors, a temperature, and looks much worse than the triage category suggests.",
    observations: "T 38.8, HR 118, BP 92/54, RR 24, SpO2 95% on air.",
    examination: "PICC line in situ, no clear chest signs, mild mucositis, cool peripheries.",
    investigations: ["Neutrophils 0.2", "Lactate 3.6", "Creatinine 132", "CXR clear", "Cultures pending"],
    choices: [
      clinicalChoices.good("ABCDE, cultures, immediate anti-pseudomonal antibiotics, fluids, oncology/microbiology advice", "Treat as time-critical sepsis with immunosuppression.", "Antibiotics are in before the clock has time to become a governance slide."),
      clinicalChoices.partial("Wait for the full blood count confirmation before antibiotics", "You recognise the issue but let a lab result slow time-critical treatment.", "The neutrophil count confirms what the history already told you."),
      clinicalChoices.unsafe("Discharge with oral antibiotics because the chest is clear", "Clear chest does not make neutropenic sepsis safe.", "The patient returns much sicker."),
    ],
  },
  {
    id: "hyponatraemia_seizure",
    title: "Symptomatic Hyponatraemia",
    locationId: "ed_resus",
    category: "emergency",
    vignette: "A patient admitted after vomiting has a brief seizure. The sodium result appears on screen at exactly the wrong moment.",
    observations: "Post-ictal, HR 102, BP 138/82, SpO2 97%, Na 112.",
    examination: "No focal neurology after recovery, dry mucosa, no meningism.",
    investigations: ["Na 112", "Serum osmolality low", "Urine sodium pending", "CT head not yet indicated"],
    choices: [
      clinicalChoices.good("Treat severe symptomatic hyponatraemia with cautious hypertonic saline bolus and senior input", "Address seizures while avoiding overcorrection.", "The sodium correction is controlled rather than theatrical."),
      clinicalChoices.partial("Fluid restrict and repeat sodium in six hours", "This may be relevant later, but seizures make it too passive now.", "The patient remains at risk while the plan waits."),
      clinicalChoices.unsafe("Give large volumes of normal saline without a correction plan", "You risk uncontrolled correction and miss the acute symptom target.", "The sodium trajectory becomes the new emergency."),
    ],
  },
  {
    id: "meningitis",
    title: "Possible Meningitis",
    locationId: "ed_resus",
    category: "urgent",
    vignette: "A 22-year-old has fever, headache, photophobia, and is becoming less coherent. CT availability is being discussed like it is the diagnosis.",
    observations: "T 39.4, HR 126, BP 108/64, RR 24, GCS 13.",
    examination: "Neck stiffness, non-blanching rash absent, no focal deficit, no papilloedema seen.",
    investigations: ["WCC 19", "CRP 180", "Glucose normal", "Coag normal"],
    choices: [
      clinicalChoices.good("Give empirical IV antibiotics promptly, assess LP safety, senior/ID input, fluids and sepsis care", "Treatment is not delayed by imaging debate.", "The antibiotics go in while the CT argument loses its oxygen."),
      clinicalChoices.partial("Wait for CT before antibiotics", "Imaging may be needed, but treatment delay is risky.", "You lose time to a scanner that was never the first treatment."),
      clinicalChoices.unsafe("Treat as migraine because there is no rash", "Absence of rash does not rule out meningitis.", "The GCS falls and the room changes temperature."),
    ],
  },
  {
    id: "adrenal_crisis",
    title: "Adrenal Crisis",
    locationId: "mau",
    category: "ambiguous",
    vignette: "A patient on long-term steroids has vomiting, abdominal pain, and blood pressure that refuses to be impressed by optimism.",
    observations: "HR 116, BP 84/48, T 37.6, glucose 3.4, Na 126, K 5.8.",
    examination: "Dehydrated, diffuse abdominal tenderness, no peritonism, steroid card in wallet.",
    investigations: ["Na 126", "K 5.8", "Glucose 3.4", "Creatinine 176", "Cortisol pending but irrelevant right now"],
    choices: [
      clinicalChoices.good("Give IV hydrocortisone immediately, fluids, glucose, treat trigger, endocrine advice", "You do not wait for cortisol before treating crisis.", "The blood pressure finally starts negotiating."),
      clinicalChoices.partial("Send cortisol and ACTH before deciding", "Useful tubes, wrong tempo.", "The diagnosis becomes clearer while the patient remains shocked."),
      clinicalChoices.unsafe("Focus on hyperkalaemia only and miss steroid dependence", "The electrolyte pattern is a clue, not the whole problem.", "The shock persists despite your narrow fix."),
    ],
  },
  {
    id: "acute_liver_failure",
    title: "Acute Liver Failure",
    locationId: "surgical",
    category: "urgent",
    vignette: "A patient with abdominal pain is drowsy, jaundiced, and has a paracetamol level nobody had checked because the story was vague.",
    observations: "HR 104, BP 106/62, RR 22, GCS 14, glucose 3.1.",
    examination: "Jaundice, tender RUQ, asterixis, no ascites, confused collateral history.",
    investigations: ["ALT 4200", "INR 3.2", "Bilirubin 86", "Paracetamol detectable", "pH 7.31"],
    choices: [
      clinicalChoices.good("Start NAC, correct glucose, discuss liver unit early, monitor encephalopathy/coagulation", "You recognise liver failure as a transfer-level problem.", "The liver unit call happens before the patient is too sick to travel."),
      clinicalChoices.partial("Repeat LFTs in four hours and ask surgeons to review", "You know it is abnormal but under-escalate the syndrome.", "The INR climbs while ownership becomes theatre."),
      clinicalChoices.unsafe("Prescribe vitamin K and leave for morning gastro review", "This misses acute liver failure and time-critical transfer.", "The patient deteriorates into a much narrower set of options."),
    ],
  },
  {
    id: "consultant_grilling",
    title: "Consultant Grilling At Handover",
    locationId: "mau",
    category: "urgent",
    vignette: "You have made it to morning handover. The consultant arrives with coffee, eye contact, and a list of apparently casual questions about the night.",
    observations: "Open tasks, ward acuity, oversight, handover quality, and every decision you made at 03:00 are now clinically relevant.",
    examination: "The consultant is calm. This is not reassuring. The day team are listening with the stillness of people who are glad it is not them.",
    investigations: ["Handover list", "Outstanding bleeps", "Ward acuity summary", "Your documentation", "One potassium result from 03:12"],
    choices: [
      {
        id: "best",
        label: "Give a structured handover: sickest patients, unresolved risks, escalation ceilings, and jobs already delegated",
        detail: "You lead with risk, uncertainty, and what needs active ownership from the day team.",
        feedback: "The consultant asks one follow-up, then nods. You have not escaped medicine, but you have survived the handover.",
        resolves: true,
        consequence: { reputation: 8, handoverQuality: 12, clinicalConfidence: 6, score: 220 },
      },
      {
        id: "partial",
        label: "List every patient chronologically and hope the important bits sound important",
        detail: "Complete-ish, but it buries the deteriorating patients among printer issues and normal troponins.",
        feedback: "The consultant rescues the structure. You survive, but the day team inherit fog.",
        resolves: true,
        consequence: { reputation: 1, handoverQuality: 2, focus: -4, score: 60 },
      },
      {
        id: "unsafe",
        label: "Say 'nothing major overnight' because technically everyone is currently alive",
        detail: "A bold strategy in front of someone who has read the bloods.",
        feedback: "The consultant opens the results page. The handover becomes educational.",
        unsafe: true,
        resolves: true,
        consequence: { reputation: -10, handoverQuality: -15, clinicalConfidence: -5, score: -160, consultantEscalations: 1 },
      },
    ],
  },
  ...scenarioPackEncounters,
];

export const pagerEvents: PagerEvent[] = [
  { id: "p_sepsis", locationId: "mau", message: "MAU: BP 78/42, looks awful, doctor aware?", sender: "Band 6 nurse", claimedUrgency: "urgent", trueUrgency: "critical", timeToDeterioration: 18, category: "emergency", encounterId: "sepsis_hypotension", ignored: { patientSafety: -22, dangerousDelays: 1, datix: 1 }, handledWell: { patientSafety: 6, score: 50 } },
  { id: "p_asthma", locationId: "ed_resus", message: "ED resus: asthma not speaking full sentences", sender: "ED registrar", claimedUrgency: "crash call-ish", trueUrgency: "critical", timeToDeterioration: 12, category: "emergency", encounterId: "acute_asthma", ignored: { patientSafety: -24, dangerousDelays: 1, consultantEscalations: 1 }, handledWell: { score: 60 } },
  { id: "p_copd", locationId: "respiratory", message: "Resp ward: COPD patient drowsy after oxygen increased", sender: "Night nurse", claimedUrgency: "urgent", trueUrgency: "high", timeToDeterioration: 22, category: "urgent", encounterId: "copd_hypercapnia", ignored: { patientSafety: -16, dangerousDelays: 1 }, handledWell: { clinicalConfidence: 2 } },
  { id: "p_nstemi", locationId: "cardiology", message: "Chest pain, ECG probably fine but could you glance?", sender: "Cardiology ward nurse", claimedUrgency: "routine", trueUrgency: "high", timeToDeterioration: 28, category: "ambiguous", encounterId: "nstemi", ignored: { patientSafety: -15, dangerousDelays: 1 }, handledWell: { score: 40 } },
  { id: "p_vt", locationId: "cardiology", message: "Telemetry is alarming and patient is sweaty", sender: "HCA via nurse", claimedUrgency: "not sure", trueUrgency: "critical", timeToDeterioration: 10, category: "emergency", encounterId: "broad_complex_tachy", ignored: { patientSafety: -28, dangerousDelays: 1, datix: 1 }, handledWell: { score: 80 } },
  { id: "p_delirium", locationId: "elderly", message: "Patient trying to leave ward, says bus is coming", sender: "Care of elderly nurse", claimedUrgency: "urgent", trueUrgency: "medium", timeToDeterioration: 35, category: "ambiguous", encounterId: "delirium", ignored: { patientSafety: -8, reputation: -3 }, handledWell: { reputation: 2 } },
  { id: "p_ugi", locationId: "surgical", message: "Surgical ward: melaena, dizzy, surgeons in theatre", sender: "Surgical nurse", claimedUrgency: "urgent", trueUrgency: "critical", timeToDeterioration: 14, category: "emergency", encounterId: "ugi_bleed", ignored: { patientSafety: -25, dangerousDelays: 1, consultantEscalations: 1 }, handledWell: { score: 70 } },
  { id: "p_dka", locationId: "mau", message: "Vomiting diabetic, ketones high, is this medical?", sender: "Triage nurse", claimedUrgency: "urgent", trueUrgency: "high", timeToDeterioration: 30, category: "urgent", encounterId: "dka", ignored: { patientSafety: -14, dangerousDelays: 1 }, handledWell: { score: 45 } },
  { id: "p_hyperk", locationId: "elderly", message: "K is 7.1 but lab says maybe repeat?", sender: "Ward nurse", claimedUrgency: "routine bloods", trueUrgency: "critical", timeToDeterioration: 14, category: "ambiguous", encounterId: "aki_hyperkalaemia", ignored: { patientSafety: -24, dangerousDelays: 1, datix: 1 }, handledWell: { score: 70 } },
  { id: "p_stroke", locationId: "ed_resus", message: "Possible stroke, unclear onset, CT are asking who owns it", sender: "ED coordinator", claimedUrgency: "urgent", trueUrgency: "high", timeToDeterioration: 26, category: "urgent", encounterId: "stroke_mimic", ignored: { patientSafety: -12, reputation: -3 }, handledWell: { reputation: 3 } },
  { id: "p_pe", locationId: "respiratory", message: "Post-op patient anxious and short of breath, CXR normal", sender: "Surgical FY1", claimedUrgency: "routine review", trueUrgency: "high", timeToDeterioration: 28, category: "ambiguous", encounterId: "pe_risk", ignored: { patientSafety: -16, dangerousDelays: 1 }, handledWell: { score: 45 } },
  { id: "p_eol", locationId: "elderly", message: "Family want everything done, patient on 15L", sender: "Ward sister", claimedUrgency: "urgent", trueUrgency: "high", timeToDeterioration: 32, category: "urgent", encounterId: "end_of_life", ignored: { patientSafety: -10, reputation: -4 }, handledWell: { reputation: 5, handoverQuality: 5 } },
  { id: "p_doctor_aware", locationId: "corridor", message: "Can you write 'doctor aware' in the notes?", sender: "Ward clerk", claimedUrgency: "now", trueUrgency: "low", timeToDeterioration: 60, category: "inappropriate", ignored: { reputation: -1 }, handledWell: { score: -10 } },
  { id: "p_drug_chart_blue", locationId: "surgical", message: "Drug chart written in blue pen, can you rewrite it?", sender: "Agency nurse", claimedUrgency: "urgent", trueUrgency: "nonsense", timeToDeterioration: 80, category: "inappropriate", ignored: { inappropriateAvoided: 1, score: 35, pagerBacklog: -1 }, handledWell: { time: 8, focus: -3, score: -20 } },
  { id: "p_printer", locationId: "estates", message: "Printer says PC LOAD LETTER. Is that medical?", sender: "Night coordinator", claimedUrgency: "life or death for labels", trueUrgency: "nonsense", timeToDeterioration: 90, category: "inappropriate", ignored: { inappropriateAvoided: 1, score: 30 }, handledWell: { time: 6, stamina: -2, score: -15 } },
  { id: "p_sandwich", locationId: "mau", message: "Patient wants to know if they can eat a sandwich before CT", sender: "HCA", claimedUrgency: "quick question", trueUrgency: "low", timeToDeterioration: 70, category: "routine", ignored: { reputation: -1 }, handledWell: { reputation: 1, time: 3 } },
  { id: "p_obs_machine", locationId: "respiratory", message: "No obs machine on ward, can you help find one?", sender: "Night nurse", claimedUrgency: "urgent-ish", trueUrgency: "medium", timeToDeterioration: 45, category: "routine", ignored: { patientSafety: -4, reputation: -2 }, handledWell: { reputation: 2, chaosSurvived: 1 } },
  { id: "p_bird", locationId: "corridor", message: "There is a bird in corridor B and it has gone towards cardiology", sender: "Switchboard", claimedUrgency: "unclear", trueUrgency: "nonsense", timeToDeterioration: 100, category: "absurd", ignored: { chaosSurvived: 1 }, handledWell: { time: 10, stamina: -4, reputation: 3, chaosSurvived: 2, score: 25 } },
  { id: "p_leak", locationId: "estates", message: "Ceiling leaking into the clean utility. Estates ask if it can wait.", sender: "Ward manager", claimedUrgency: "not medical but help", trueUrgency: "medium", timeToDeterioration: 50, category: "absurd", ignored: { patientSafety: -3, chaosSurvived: 1 }, handledWell: { time: 7, reputation: 2, chaosSurvived: 2 } },
  { id: "p_kettle", locationId: "mess", message: "Mess kettle has tripped the socket and morale is falling", sender: "FY1", claimedUrgency: "catastrophic", trueUrgency: "nonsense", timeToDeterioration: 90, category: "absurd", ignored: { stamina: -1 }, handledWell: { time: 5, reputation: 1, chaosSurvived: 1 } },
  { id: "p_radiology", locationId: "radiology", message: "CT request rejected: 'please correlate clinically'", sender: "Radiographer", claimedUrgency: "routine admin", trueUrgency: "medium", timeToDeterioration: 45, category: "ambiguous", ignored: { patientSafety: -5, reputation: -1 }, handledWell: { reputation: 2, score: 20 } },
  { id: "p_pharmacy", locationId: "pharmacy", message: "Only gentamicin level machine is down. Need plan.", sender: "On-call pharmacist", claimedUrgency: "urgent", trueUrgency: "medium", timeToDeterioration: 40, category: "urgent", ignored: { patientSafety: -6, reputation: -2 }, handledWell: { reputation: 3, clinicalConfidence: 1 } },
  { id: "p_swipe", locationId: "lifts", message: "Swipe access to stairwell failed, nurse trapped between doors metaphorically", sender: "Site practitioner", claimedUrgency: "urgent", trueUrgency: "low", timeToDeterioration: 70, category: "routine", ignored: { reputation: -2 }, handledWell: { chaosSurvived: 1, reputation: 1 } },
  { id: "p_bed", locationId: "mau", message: "Bed manager asks if three patients can be discharged by instinct", sender: "Bed manager", claimedUrgency: "immediate", trueUrgency: "low", timeToDeterioration: 75, category: "routine", ignored: { reputation: -1 }, handledWell: { time: 6, focus: -4, reputation: 2 } },
  { id: "p_missing_chart", locationId: "surgical", message: "Missing drug chart; patient due Parkinson's meds", sender: "Surgical nurse", claimedUrgency: "urgent", trueUrgency: "medium", timeToDeterioration: 35, category: "ambiguous", ignored: { patientSafety: -7, reputation: -2 }, handledWell: { reputation: 3, score: 25 } },
  { id: "p_epr_down", locationId: "corridor", message: "EPR downtime. Nobody can see bloods unless they remember paper.", sender: "Site practitioner", claimedUrgency: "hospital-wide", trueUrgency: "medium", timeToDeterioration: 60, category: "routine", ignored: { focus: -3, pagerBacklog: 1 }, handledWell: { chaosSurvived: 2, handoverQuality: 2 } },
  { id: "p_cannulas", locationId: "mau", message: "There are no pink cannulas in the cupboard. Only vibes.", sender: "FY1", claimedUrgency: "urgent", trueUrgency: "medium", timeToDeterioration: 50, category: "routine", ignored: { stamina: -2, reputation: -1 }, handledWell: { time: 5, reputation: 2, chaosSurvived: 1 } },
];

const extraTaskTemplates: TaskTemplate[] = [
  { id: "t_reg_1", locationId: "respiratory", message: "Reg Sense: day handover said 'COPD, probably fine' but the ABG was never repeated.", sender: "Your reg sense", source: "reg_sense", claimedUrgency: "vague", trueUrgency: "high", category: "ambiguous", encounterId: "copd_hypercapnia", timeToDeterioration: 24, vague: true, regSense: true, weight: 12, ignored: { patientSafety: -13, dangerousDelays: 1 }, handledWell: { score: 55, clinicalConfidence: 3 } },
  { id: "t_reg_2", locationId: "elderly", message: "Reg Sense: 'pleasantly confused' is doing too much work in the handover.", sender: "Your reg sense", source: "reg_sense", claimedUrgency: "soft signal", trueUrgency: "medium", category: "ambiguous", encounterId: "delirium", timeToDeterioration: 34, vague: true, regSense: true, weight: 10, ignored: { patientSafety: -8, reputation: -2 }, handledWell: { score: 45, clinicalConfidence: 2 } },
  { id: "t_reg_3", locationId: "cardiology", message: "Reg Sense: troponin labelled 'await repeat' but the ECG description sounds dynamic.", sender: "Your reg sense", source: "reg_sense", claimedUrgency: "hmm", trueUrgency: "high", category: "ambiguous", encounterId: "nstemi", timeToDeterioration: 26, vague: true, regSense: true, weight: 10, ignored: { patientSafety: -12, dangerousDelays: 1 }, handledWell: { score: 50, clinicalConfidence: 3 } },
  { id: "t_reg_4", locationId: "surgical", message: "Reg Sense: 'medical optimisation' plus no obs is never a complete sentence.", sender: "Your reg sense", source: "reg_sense", claimedUrgency: "thin handover", trueUrgency: "medium", category: "ambiguous", encounterId: "acute_liver_failure", timeToDeterioration: 36, vague: true, regSense: true, weight: 9, ignored: { patientSafety: -10, reputation: -2 }, handledWell: { score: 50, clinicalConfidence: 2 } },
  { id: "t_reg_5", locationId: "mau", message: "Reg Sense: chemotherapy patient with 'viral symptoms' has a temperature trend nobody likes.", sender: "Your reg sense", source: "reg_sense", claimedUrgency: "vague", trueUrgency: "critical", category: "ambiguous", encounterId: "neutropenic_sepsis", timeToDeterioration: 18, vague: true, regSense: true, weight: 11, phases: ["deep", "pre_handover"], ignored: { patientSafety: -20, dangerousDelays: 1, datix: 1 }, handledWell: { score: 65, clinicalConfidence: 3 } },
  { id: "t_neutro", locationId: "mau", message: "MAU: chemo patient febrile, triage asks if they can wait for cubicle.", sender: "Triage nurse", source: "pager", claimedUrgency: "urgent", trueUrgency: "critical", category: "emergency", encounterId: "neutropenic_sepsis", timeToDeterioration: 14, weight: 10, ignored: { patientSafety: -24, dangerousDelays: 1 }, handledWell: { score: 70 } },
  { id: "t_hypona", locationId: "ed_resus", message: "ED: seizure, sodium has just come back 112.", sender: "ED nurse", source: "pager", claimedUrgency: "crash call", trueUrgency: "critical", category: "emergency", encounterId: "hyponatraemia_seizure", timeToDeterioration: 12, weight: 8, ignored: { patientSafety: -20, dangerousDelays: 1 }, handledWell: { score: 70 } },
  { id: "t_meningitis", locationId: "ed_resus", message: "ED: fever, headache, photophobia, CT discussion spiralling.", sender: "ED SHO", source: "pager", claimedUrgency: "urgent", trueUrgency: "high", category: "urgent", encounterId: "meningitis", timeToDeterioration: 22, weight: 8, ignored: { patientSafety: -16, dangerousDelays: 1 }, handledWell: { score: 60 } },
  { id: "t_adrenal", locationId: "mau", message: "MAU: vomiting steroid patient hypotensive despite fluids.", sender: "Nurse in charge", source: "pager", claimedUrgency: "urgent", trueUrgency: "high", category: "ambiguous", encounterId: "adrenal_crisis", timeToDeterioration: 24, weight: 9, ignored: { patientSafety: -15, dangerousDelays: 1 }, handledWell: { clinicalConfidence: 3, score: 55 } },
  { id: "t_liver", locationId: "surgical", message: "Surgical ward: jaundiced abdominal pain patient now drowsy, INR scary.", sender: "Surgical FY1", source: "pager", claimedUrgency: "urgent", trueUrgency: "high", category: "urgent", encounterId: "acute_liver_failure", timeToDeterioration: 25, weight: 8, ignored: { patientSafety: -16, dangerousDelays: 1 }, handledWell: { score: 60 } },
  { id: "t_bloods_vague", locationId: "mau", message: "Handover task: 'review bloods overnight' with no indication and three red exclamation marks.", sender: "Day team list", source: "handover", claimedUrgency: "unclear", trueUrgency: "medium", category: "ambiguous", encounterId: "aki_hyperkalaemia", timeToDeterioration: 34, vague: true, weight: 7, ignored: { patientSafety: -8, handoverQuality: -2 }, handledWell: { score: 35, handoverQuality: 2 } },
  { id: "t_anticoag", locationId: "cardiology", message: "Handover task: anticoagulation plan says 'decide later' next to new AF and falling Hb.", sender: "Day team list", source: "handover", claimedUrgency: "review", trueUrgency: "medium", category: "ambiguous", encounterId: "ugi_bleed", timeToDeterioration: 38, vague: true, weight: 6, ignored: { patientSafety: -8, handoverQuality: -3 }, handledWell: { score: 35, clinicalConfidence: 2 } },
  { id: "t_niv_machine", locationId: "respiratory", message: "Resp ward: only NIV machine has a missing connector.", sender: "Respiratory nurse", source: "system", claimedUrgency: "before it matters", trueUrgency: "medium", category: "routine", timeToDeterioration: 42, weight: 7, ignored: { patientSafety: -5, reputation: -2, chaosSurvived: 1 }, handledWell: { time: 6, reputation: 3, chaosSurvived: 2, score: 25 } },
  { id: "t_porter_delay", locationId: "corridor", message: "Portering delay: blood cultures and urgent samples are touring the hospital without purpose.", sender: "Site practitioner", source: "system", claimedUrgency: "flow issue", trueUrgency: "medium", category: "routine", timeToDeterioration: 45, weight: 7, ignored: { patientSafety: -4, focus: -2 }, handledWell: { reputation: 2, chaosSurvived: 2, score: 25 } },
  { id: "t_short_staffed", locationId: "elderly", message: "Care of elderly: two nurses down and four patients need neuro obs.", sender: "Ward sister", source: "system", claimedUrgency: "staffing", trueUrgency: "medium", category: "routine", timeToDeterioration: 44, weight: 8, ignored: { patientSafety: -6, reputation: -2 }, handledWell: { reputation: 3, chaosSurvived: 2, score: 30 } },
  { id: "t_epr_med_rec", locationId: "pharmacy", message: "EPR downtime has swallowed the medicines reconciliation for three new admissions.", sender: "On-call pharmacist", source: "system", claimedUrgency: "admin", trueUrgency: "medium", category: "routine", timeToDeterioration: 50, weight: 6, ignored: { patientSafety: -5, handoverQuality: -2 }, handledWell: { reputation: 3, handoverQuality: 2, chaosSurvived: 2 } },
  { id: "t_relatives", locationId: "elderly", message: "Family update request is becoming a complaint because the plan is unclear.", sender: "Ward clerk", source: "system", claimedUrgency: "communication", trueUrgency: "low", category: "routine", timeToDeterioration: 60, weight: 5, ignored: { reputation: -5, handoverQuality: -1 }, handledWell: { reputation: 4, handoverQuality: 2, score: 20 } },
  { id: "t_bed_gridlock", locationId: "mau", message: "Site meeting: MAU has no beds, ED has ambulances queueing, and three decisions need a med reg.", sender: "Bed manager", source: "system", claimedUrgency: "hospital pressure", trueUrgency: "medium", category: "routine", timeToDeterioration: 48, weight: 7, ignored: { patientSafety: -5, reputation: -3, pagerBacklog: 1 }, handledWell: { reputation: 3, chaosSurvived: 2, score: 25 } },
  { id: "t_abg_cartridge", locationId: "respiratory", message: "ABG analyser is out of cartridges just as three gases are due.", sender: "Respiratory ward", source: "system", claimedUrgency: "kit failure", trueUrgency: "medium", category: "routine", timeToDeterioration: 38, weight: 7, ignored: { patientSafety: -5, reputation: -2 }, handledWell: { time: 5, reputation: 2, chaosSurvived: 2 } },
  { id: "t_drug_cupboard", locationId: "surgical", message: "Controlled drug cupboard keys have gone on an unscheduled tour of the hospital.", sender: "Surgical nurse", source: "system", claimedUrgency: "pain control", trueUrgency: "medium", category: "routine", timeToDeterioration: 42, weight: 6, ignored: { patientSafety: -4, reputation: -3 }, handledWell: { reputation: 3, chaosSurvived: 2, score: 20 } },
  { id: "t_ct_porter", locationId: "radiology", message: "CT slot available now, but no porter and the patient is on oxygen.", sender: "Radiographer", source: "system", claimedUrgency: "logistics", trueUrgency: "medium", category: "routine", timeToDeterioration: 30, weight: 7, ignored: { patientSafety: -6, reputation: -2 }, handledWell: { reputation: 3, chaosSurvived: 2, score: 25 } },
  { id: "t_isolation_bay", locationId: "mau", message: "Possible infectious diarrhoea has been placed in the only empty bay.", sender: "Nurse in charge", source: "system", claimedUrgency: "infection control", trueUrgency: "medium", category: "routine", timeToDeterioration: 46, weight: 5, ignored: { patientSafety: -4, chaosSurvived: -1 }, handledWell: { reputation: 2, chaosSurvived: 2, score: 20 } },
  { id: "t_oxygen_ports", locationId: "ed_resus", message: "Two oxygen ports are faulty in resus and estates want a clinical priority list.", sender: "ED coordinator", source: "system", claimedUrgency: "estates", trueUrgency: "medium", category: "routine", timeToDeterioration: 36, weight: 6, ignored: { patientSafety: -6, reputation: -2 }, handledWell: { reputation: 3, chaosSurvived: 2 } },
  { id: "t_discharge_lounge", locationId: "elderly", message: "Discharge lounge is closed; four medically fit patients are blocking escalation beds.", sender: "Site practitioner", source: "system", claimedUrgency: "flow", trueUrgency: "low", category: "routine", timeToDeterioration: 58, weight: 5, ignored: { reputation: -2, pagerBacklog: 1 }, handledWell: { reputation: 2, chaosSurvived: 2, score: 20 } },
  { id: "t_pharmacy_code", locationId: "pharmacy", message: "The emergency cupboard code has changed and nobody on nights has been told.", sender: "FY1", source: "system", claimedUrgency: "access", trueUrgency: "medium", category: "routine", timeToDeterioration: 44, weight: 6, ignored: { patientSafety: -4, reputation: -2 }, handledWell: { reputation: 3, chaosSurvived: 2 } },
  { id: "t_stairwell_alarm", locationId: "lifts", message: "The stairwell alarm sounds every time staff bypass the broken lift.", sender: "Security", source: "system", claimedUrgency: "noise and access", trueUrgency: "low", category: "absurd", timeToDeterioration: 65, weight: 4, ignored: { focus: -4, reputation: -1 }, handledWell: { chaosSurvived: 2, score: 15 } },
  { id: "t_specimen_pod", locationId: "corridor", message: "Specimen pod system is down; urgent bloods need a human courier.", sender: "Site practitioner", source: "system", claimedUrgency: "transport", trueUrgency: "medium", category: "routine", timeToDeterioration: 40, weight: 6, ignored: { patientSafety: -5, focus: -2 }, handledWell: { reputation: 2, chaosSurvived: 2, score: 20 } },
  { id: "t_fox_ambulance_bay", locationId: "ed_resus", message: "Security report a fox in the ambulance bay and one paramedic is refusing to negotiate.", sender: "ED coordinator", source: "system", claimedUrgency: "wildlife flow issue", trueUrgency: "low", category: "absurd", timeToDeterioration: 62, weight: 4, ignored: { reputation: -1, chaosSurvived: 1 }, handledWell: { time: 5, reputation: 2, chaosSurvived: 2, score: 20 } },
  { id: "t_cat_linen", locationId: "elderly", message: "A cat has been found asleep in the clean linen cupboard. Nobody knows whose cat.", sender: "Ward sister", source: "system", claimedUrgency: "infection control-ish", trueUrgency: "low", category: "absurd", timeToDeterioration: 75, weight: 4, ignored: { reputation: -2, focus: -1 }, handledWell: { time: 4, reputation: 3, chaosSurvived: 2, score: 20 } },
  { id: "t_dog_relatives", locationId: "surgical", message: "A relative has brought a dog onto the surgical ward and says it is 'basically therapeutic'.", sender: "Surgical nurse", source: "system", claimedUrgency: "policy question", trueUrgency: "low", category: "absurd", timeToDeterioration: 70, weight: 4, ignored: { reputation: -2, chaosSurvived: 1 }, handledWell: { time: 5, reputation: 2, chaosSurvived: 2, score: 15 } },
  { id: "t_bat_stairwell", locationId: "lifts", message: "There is a bat in the stairwell and the lift is still broken.", sender: "Switchboard", source: "system", claimedUrgency: "estates? infection control? vibes?", trueUrgency: "medium", category: "absurd", timeToDeterioration: 44, weight: 5, ignored: { focus: -4, reputation: -2, pagerBacklog: 1 }, handledWell: { time: 7, reputation: 3, chaosSurvived: 3, score: 25 } },
  { id: "t_mouse_mess", locationId: "mess", message: "A mouse has appeared in the doctors' mess and is making better use of the snack cupboard than you are.", sender: "FY1", source: "system", claimedUrgency: "morale emergency", trueUrgency: "nonsense", category: "absurd", timeToDeterioration: 90, weight: 4, ignored: { stamina: -2, focus: -1 }, handledWell: { time: 4, reputation: 1, chaosSurvived: 2, score: 15 } },
  { id: "t_squirrel_pharmacy", locationId: "pharmacy", message: "On-call pharmacy says a squirrel is between them and the emergency cupboard.", sender: "On-call pharmacist", source: "system", claimedUrgency: "access issue with tail", trueUrgency: "low", category: "absurd", timeToDeterioration: 68, weight: 4, ignored: { patientSafety: -2, reputation: -1 }, handledWell: { time: 5, reputation: 2, chaosSurvived: 2, score: 20 } },
];

export const taskTemplates: TaskTemplate[] = [
  ...pagerEvents.map((event) => ({
    ...event,
    source: "pager" as const,
    weight: event.trueUrgency === "critical" ? 10 : event.trueUrgency === "high" ? 8 : event.trueUrgency === "medium" ? 6 : 4,
    vague: event.category === "ambiguous",
    regSense: false,
  })),
  ...extraTaskTemplates,
  ...scenarioPackTasks,
  ...regSensePackTasks,
  ...bleepPackTasks,
];

export const allyNames = ["Experienced night nurse", "Helpful SHO", "ICU registrar", "Radiographer who trusts good referrals", "Bed manager", "Pharmacist on call", "Porter who knows shortcuts"];
export const itemNames = ["Coffee", "Snack", "Guideline app", "ABG kit", "Cannula kit", "Consultant advice token", "Radiology persuasion token", "Handover notes"];
