import type { TaskTemplate } from "./types";

type RegSensePackItem = Omit<TaskTemplate, "encounterId"> & {
  encounterId: string | null;
};

const rawRegSensePack: RegSensePackItem[] = [
  {
    id: "too_relaxed_handover_sats",
    locationId: "mau",
    message:
      "Reg Sense: handover says 'just keep an eye on sats' but the oxygen column has quietly changed twice.",
    sender: "Your reg sense",
    source: "reg_sense",
    claimedUrgency: "thin handover",
    trueUrgency: "high",
    category: "ambiguous",
    encounterId: null,
    timeToDeterioration: 45,
    vague: true,
    regSense: true,
    revealAtIntel1: "Checked the notes — O2 went from 2L to 4L to now 6L over three hours. Nobody has written why. Sats currently 93%.",
    revealAtIntel2: "Spoke to the nurse: patient has been increasing work of breathing over the past hour. No clear cause documented. Chest sounds wet on brief assessment — likely fluid overload or occult pneumonia.",
    weight: 9,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -8,
      reputation: -2,
      dangerousDelays: 1,
      datix: 0,
      handoverQuality: -2,
    },
    handledWell: {
      score: 50,
      clinicalConfidence: 3,
      patientSafety: 3,
      handoverQuality: 2,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login", "bed_manager"],
    delegationDuration: {},
  },
  {
    id: "unowned_rising_potassium",
    locationId: "elderly",
    message:
      "Reg Sense: potassium is labelled 'await repeat' but nobody seems to own the first result.",
    sender: "Your reg sense",
    source: "reg_sense",
    claimedUrgency: "soft signal",
    trueUrgency: "critical",
    category: "ambiguous",
    encounterId: null,
    timeToDeterioration: 20,
    vague: true,
    regSense: true,
    revealAtIntel1: "Pulled the result — K+ 6.1 from four hours ago, flagged critical by lab. Repeat is still 'pending'. Patient has AKI on background CKD.",
    revealAtIntel2: "ECG shows peaked T waves and a slightly wide QRS. Patient is oliguric. This is hyperkalaemic emergency — needs calcium gluconate and urgent treatment, not just a repeat blood.",
    weight: 12,
    phases: ["early", "deep", "pre_handover"],
    ignored: {
      patientSafety: -8,
      reputation: -2,
      dangerousDelays: 1,
      datix: 0,
      handoverQuality: -2,
    },
    handledWell: {
      score: 50,
      clinicalConfidence: 3,
      patientSafety: 3,
      handoverQuality: 2,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login", "bed_manager"],
    delegationDuration: {},
  },
  {
    id: "await_repeat_lactate",
    locationId: "ed_resus",
    message:
      "Reg Sense: the lactate is written as 'await repeat' but the patient is already on their second bag of fluid.",
    sender: "Your reg sense",
    source: "reg_sense",
    claimedUrgency: "pattern recognition",
    trueUrgency: "critical",
    category: "ambiguous",
    encounterId: null,
    timeToDeterioration: 15,
    vague: true,
    regSense: true,
    weight: 12,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -8,
      reputation: -2,
      dangerousDelays: 1,
      datix: 0,
      handoverQuality: -2,
    },
    handledWell: {
      score: 50,
      clinicalConfidence: 3,
      patientSafety: 3,
      handoverQuality: 2,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login", "bed_manager"],
    delegationDuration: {},
  },
  {
    id: "nurse_not_happy_numbers_ok",
    locationId: "respiratory",
    message:
      "Reg Sense: nurse says they are 'just not happy' despite observations that do not quite trigger escalation.",
    sender: "Your reg sense",
    source: "reg_sense",
    claimedUrgency: "unease",
    trueUrgency: "high",
    category: "ambiguous",
    encounterId: null,
    timeToDeterioration: 40,
    vague: true,
    regSense: true,
    weight: 10,
    phases: ["early", "deep", "pre_handover"],
    ignored: {
      patientSafety: -8,
      reputation: -2,
      dangerousDelays: 1,
      datix: 0,
      handoverQuality: -2,
    },
    handledWell: {
      score: 50,
      clinicalConfidence: 3,
      patientSafety: 3,
      handoverQuality: 2,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login", "bed_manager"],
    delegationDuration: {},
  },
  {
    id: "family_not_themselves",
    locationId: "elderly",
    message:
      "Reg Sense: family keep saying 'they are not themselves' but the notes call it baseline confusion.",
    sender: "Your reg sense",
    source: "reg_sense",
    claimedUrgency: "soft signal",
    trueUrgency: "high",
    category: "ambiguous",
    encounterId: null,
    timeToDeterioration: 60,
    vague: true,
    regSense: true,
    weight: 9,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -8,
      reputation: -2,
      dangerousDelays: 1,
      datix: 0,
      handoverQuality: -2,
    },
    handledWell: {
      score: 50,
      clinicalConfidence: 3,
      patientSafety: 3,
      handoverQuality: 2,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login", "bed_manager"],
    delegationDuration: {},
  },
  {
    id: "readmission_too_fast",
    locationId: "mau",
    message:
      "Reg Sense: patient discharged yesterday is back tonight and the clerking reads almost identical.",
    sender: "Your reg sense",
    source: "reg_sense",
    claimedUrgency: "pattern recognition",
    trueUrgency: "medium",
    category: "ambiguous",
    encounterId: null,
    timeToDeterioration: 75,
    vague: true,
    regSense: true,
    weight: 7,
    phases: ["early", "pre_handover"],
    ignored: {
      patientSafety: -8,
      reputation: -2,
      dangerousDelays: 1,
      datix: 0,
      handoverQuality: -2,
    },
    handledWell: {
      score: 50,
      clinicalConfidence: 3,
      patientSafety: 3,
      handoverQuality: 2,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login", "bed_manager"],
    delegationDuration: {},
  },
  {
    id: "anticoagulation_ambiguous_fall",
    locationId: "elderly",
    message:
      "Reg Sense: fall described as 'minor' but anticoagulation status is copied forward and uncertain.",
    sender: "Your reg sense",
    source: "reg_sense",
    claimedUrgency: "thin handover",
    trueUrgency: "high",
    category: "ambiguous",
    encounterId: null,
    timeToDeterioration: 50,
    vague: true,
    regSense: true,
    weight: 10,
    phases: ["deep", "pre_handover"],
    ignored: {
      patientSafety: -8,
      reputation: -2,
      dangerousDelays: 1,
      datix: 0,
      handoverQuality: -2,
    },
    handledWell: {
      score: 50,
      clinicalConfidence: 3,
      patientSafety: 3,
      handoverQuality: 2,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login", "bed_manager"],
    delegationDuration: {},
  },
  {
    id: "steroid_abdominal_vague",
    locationId: "mau",
    message:
      "Reg Sense: chronic steroid patient has vague abdominal pain and looks better on paper than from the doorway.",
    sender: "Your reg sense",
    source: "reg_sense",
    claimedUrgency: "unease",
    trueUrgency: "high",
    category: "ambiguous",
    encounterId: null,
    timeToDeterioration: 45,
    vague: true,
    regSense: true,
    weight: 10,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -8,
      reputation: -2,
      dangerousDelays: 1,
      datix: 0,
      handoverQuality: -2,
    },
    handledWell: {
      score: 50,
      clinicalConfidence: 3,
      patientSafety: 3,
      handoverQuality: 2,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login", "bed_manager"],
    delegationDuration: {},
  },
  {
    id: "chemo_viral_symptoms",
    locationId: "mau",
    message:
      "Reg Sense: recent chemo patient is labelled 'viral' but nobody has mentioned neutrophils yet.",
    sender: "Your reg sense",
    source: "reg_sense",
    claimedUrgency: "pattern recognition",
    trueUrgency: "critical",
    category: "ambiguous",
    encounterId: null,
    timeToDeterioration: 25,
    vague: true,
    regSense: true,
    weight: 12,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -8,
      reputation: -2,
      dangerousDelays: 1,
      datix: 0,
      handoverQuality: -2,
    },
    handledWell: {
      score: 50,
      clinicalConfidence: 3,
      patientSafety: 3,
      handoverQuality: 2,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login", "bed_manager"],
    delegationDuration: {},
  },
  {
    id: "delirium_baseline_no_collateral",
    locationId: "elderly",
    message:
      "Reg Sense: 'baseline dementia' appears in three notes but there is no collateral history.",
    sender: "Your reg sense",
    source: "reg_sense",
    claimedUrgency: "thin handover",
    trueUrgency: "medium",
    category: "ambiguous",
    encounterId: null,
    timeToDeterioration: 90,
    vague: true,
    regSense: true,
    weight: 6,
    phases: ["early", "pre_handover"],
    ignored: {
      patientSafety: -8,
      reputation: -2,
      dangerousDelays: 1,
      datix: 0,
      handoverQuality: -2,
    },
    handledWell: {
      score: 50,
      clinicalConfidence: 3,
      patientSafety: 3,
      handoverQuality: 2,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login", "bed_manager"],
    delegationDuration: {},
  },
  {
    id: "ecg_probably_fine",
    locationId: "cardiology",
    message:
      "Reg Sense: ECG is described as 'probably fine' but nobody sounds completely convinced.",
    sender: "Your reg sense",
    source: "reg_sense",
    claimedUrgency: "vague",
    trueUrgency: "high",
    category: "ambiguous",
    encounterId: null,
    timeToDeterioration: 30,
    vague: true,
    regSense: true,
    weight: 10,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -8,
      reputation: -2,
      dangerousDelays: 1,
      datix: 0,
      handoverQuality: -2,
    },
    handledWell: {
      score: 50,
      clinicalConfidence: 3,
      patientSafety: 3,
      handoverQuality: 2,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login", "bed_manager"],
    delegationDuration: {},
  },
  {
    id: "radiology_rejected_trajectory",
    locationId: "surgical",
    message:
      "Reg Sense: scan request was rejected as low yield, but the patient trajectory has not read the rejection email.",
    sender: "Your reg sense",
    source: "reg_sense",
    claimedUrgency: "unease",
    trueUrgency: "high",
    category: "ambiguous",
    encounterId: null,
    timeToDeterioration: 55,
    vague: true,
    regSense: true,
    weight: 9,
    phases: ["deep", "pre_handover"],
    ignored: {
      patientSafety: -8,
      reputation: -2,
      dangerousDelays: 1,
      datix: 0,
      handoverQuality: -2,
    },
    handledWell: {
      score: 50,
      clinicalConfidence: 3,
      patientSafety: 3,
      handoverQuality: 2,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login", "bed_manager"],
    delegationDuration: {},
  },
  {
    id: "end_of_life_plan_unclear",
    locationId: "respiratory",
    message:
      "Reg Sense: end-of-life plan says 'for comfort' but the escalation box is blank.",
    sender: "Your reg sense",
    source: "reg_sense",
    claimedUrgency: "thin handover",
    trueUrgency: "medium",
    category: "ambiguous",
    encounterId: null,
    timeToDeterioration: 90,
    vague: true,
    regSense: true,
    weight: 7,
    phases: ["deep", "pre_handover"],
    ignored: {
      patientSafety: -8,
      reputation: -2,
      dangerousDelays: 1,
      datix: 0,
      handoverQuality: -2,
    },
    handledWell: {
      score: 50,
      clinicalConfidence: 3,
      patientSafety: 3,
      handoverQuality: 2,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login", "bed_manager"],
    delegationDuration: {},
  },
  {
    id: "parkinsons_meds_missed",
    locationId: "elderly",
    message:
      "Reg Sense: Parkinson's meds are marked 'not given' and the patient is now oddly quiet.",
    sender: "Your reg sense",
    source: "reg_sense",
    claimedUrgency: "soft signal",
    trueUrgency: "high",
    category: "ambiguous",
    encounterId: null,
    timeToDeterioration: 60,
    vague: true,
    regSense: true,
    weight: 9,
    phases: ["deep", "pre_handover"],
    ignored: {
      patientSafety: -8,
      reputation: -2,
      dangerousDelays: 1,
      datix: 0,
      handoverQuality: -2,
    },
    handledWell: {
      score: 50,
      clinicalConfidence: 3,
      patientSafety: 3,
      handoverQuality: 2,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login", "bed_manager"],
    delegationDuration: {},
  },
  {
    id: "frailty_quiet_deterioration",
    locationId: "elderly",
    message:
      "Reg Sense: frailty patient has not triggered NEWS, but every observation is a little worse than the last one.",
    sender: "Your reg sense",
    source: "reg_sense",
    claimedUrgency: "pattern recognition",
    trueUrgency: "high",
    category: "ambiguous",
    encounterId: null,
    timeToDeterioration: 70,
    vague: true,
    regSense: true,
    weight: 8,
    phases: ["early", "deep", "pre_handover"],
    ignored: {
      patientSafety: -8,
      reputation: -2,
      dangerousDelays: 1,
      datix: 0,
      handoverQuality: -2,
    },
    handledWell: {
      score: 50,
      clinicalConfidence: 3,
      patientSafety: 3,
      handoverQuality: 2,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login", "bed_manager"],
    delegationDuration: {},
  },
  {
    id: "oxygen_creeping_post_nebs",
    locationId: "respiratory",
    message:
      "Reg Sense: oxygen requirement is creeping up while everyone talks about 'just giving another neb'.",
    sender: "Your reg sense",
    source: "reg_sense",
    claimedUrgency: "pattern recognition",
    trueUrgency: "critical",
    category: "ambiguous",
    encounterId: null,
    timeToDeterioration: 25,
    vague: true,
    regSense: true,
    weight: 12,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -8,
      reputation: -2,
      dangerousDelays: 1,
      datix: 0,
      handoverQuality: -2,
    },
    handledWell: {
      score: 50,
      clinicalConfidence: 3,
      patientSafety: 3,
      handoverQuality: 2,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login", "bed_manager"],
    delegationDuration: {},
  },
  {
    id: "repeat_troponin_waiting",
    locationId: "cardiology",
    message:
      "Reg Sense: repeat troponin is pending, but the pain story changed while nobody was looking.",
    sender: "Your reg sense",
    source: "reg_sense",
    claimedUrgency: "soft signal",
    trueUrgency: "high",
    category: "ambiguous",
    encounterId: null,
    timeToDeterioration: 45,
    vague: true,
    regSense: true,
    weight: 10,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -8,
      reputation: -2,
      dangerousDelays: 1,
      datix: 0,
      handoverQuality: -2,
    },
    handledWell: {
      score: 50,
      clinicalConfidence: 3,
      patientSafety: 3,
      handoverQuality: 2,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login", "bed_manager"],
    delegationDuration: {},
  },
  {
    id: "hyponatraemia_no_owner",
    locationId: "mau",
    message:
      "Reg Sense: sodium is low enough to matter, but the plan says only 'repeat U&E in morning'.",
    sender: "Your reg sense",
    source: "reg_sense",
    claimedUrgency: "thin handover",
    trueUrgency: "high",
    category: "ambiguous",
    encounterId: null,
    timeToDeterioration: 80,
    vague: true,
    regSense: true,
    weight: 8,
    phases: ["deep", "pre_handover"],
    ignored: {
      patientSafety: -8,
      reputation: -2,
      dangerousDelays: 1,
      datix: 0,
      handoverQuality: -2,
    },
    handledWell: {
      score: 50,
      clinicalConfidence: 3,
      patientSafety: 3,
      handoverQuality: 2,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login", "bed_manager"],
    delegationDuration: {},
  },
  {
    id: "soft_bp_normalised",
    locationId: "mau",
    message:
      "Reg Sense: blood pressure has 'improved' but only after the cuff moved arms and the patient stopped talking.",
    sender: "Your reg sense",
    source: "reg_sense",
    claimedUrgency: "unease",
    trueUrgency: "critical",
    category: "ambiguous",
    encounterId: null,
    timeToDeterioration: 20,
    vague: true,
    regSense: true,
    weight: 12,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -8,
      reputation: -2,
      dangerousDelays: 1,
      datix: 0,
      handoverQuality: -2,
    },
    handledWell: {
      score: 50,
      clinicalConfidence: 3,
      patientSafety: 3,
      handoverQuality: 2,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login", "bed_manager"],
    delegationDuration: {},
  },
  {
    id: "dka_possible_not_named",
    locationId: "ed_resus",
    message:
      "Reg Sense: glucose is high, ketones are tucked in the triage notes, and nobody has said DKA aloud.",
    sender: "Your reg sense",
    source: "reg_sense",
    claimedUrgency: "pattern recognition",
    trueUrgency: "critical",
    category: "ambiguous",
    encounterId: null,
    timeToDeterioration: 30,
    vague: true,
    regSense: true,
    weight: 12,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -8,
      reputation: -2,
      dangerousDelays: 1,
      datix: 0,
      handoverQuality: -2,
    },
    handledWell: {
      score: 50,
      clinicalConfidence: 3,
      patientSafety: 3,
      handoverQuality: 2,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login", "bed_manager"],
    delegationDuration: {},
  },
  {
    id: "icu_referral_not_yet",
    locationId: "icu",
    message:
      "Reg Sense: everyone says 'not for ICU yet' but nobody has defined what 'yet' means.",
    sender: "Your reg sense",
    source: "reg_sense",
    claimedUrgency: "vague",
    trueUrgency: "high",
    category: "ambiguous",
    encounterId: null,
    timeToDeterioration: 35,
    vague: true,
    regSense: true,
    weight: 10,
    phases: ["deep", "pre_handover"],
    ignored: {
      patientSafety: -8,
      reputation: -2,
      dangerousDelays: 1,
      datix: 0,
      handoverQuality: -2,
    },
    handledWell: {
      score: 50,
      clinicalConfidence: 3,
      patientSafety: 3,
      handoverQuality: 2,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login", "bed_manager"],
    delegationDuration: {},
  },
  {
    id: "copd_co2_quiet",
    locationId: "respiratory",
    message:
      "Reg Sense: COPD patient is less agitated now, but the oxygen has gone up and no gas has been repeated.",
    sender: "Your reg sense",
    source: "reg_sense",
    claimedUrgency: "pattern recognition",
    trueUrgency: "critical",
    category: "ambiguous",
    encounterId: null,
    timeToDeterioration: 25,
    vague: true,
    regSense: true,
    weight: 12,
    phases: ["deep", "pre_handover"],
    ignored: {
      patientSafety: -8,
      reputation: -2,
      dangerousDelays: 1,
      datix: 0,
      handoverQuality: -2,
    },
    handledWell: {
      score: 50,
      clinicalConfidence: 3,
      patientSafety: 3,
      handoverQuality: 2,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login", "bed_manager"],
    delegationDuration: {},
  },
  {
    id: "missed_antibiotic_ownership",
    locationId: "surgical",
    message:
      "Reg Sense: antibiotics are 'due after cultures' but nobody knows whether cultures have actually been sent.",
    sender: "Your reg sense",
    source: "reg_sense",
    claimedUrgency: "soft signal",
    trueUrgency: "high",
    category: "ambiguous",
    encounterId: null,
    timeToDeterioration: 50,
    vague: true,
    regSense: true,
    weight: 9,
    phases: ["early", "deep"],
    ignored: {
      patientSafety: -8,
      reputation: -2,
      dangerousDelays: 1,
      datix: 0,
      handoverQuality: -2,
    },
    handledWell: {
      score: 50,
      clinicalConfidence: 3,
      patientSafety: 3,
      handoverQuality: 2,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login", "bed_manager"],
    delegationDuration: {},
  },
  {
    id: "syncope_parked_as_mechanical_fall",
    locationId: "elderly",
    message:
      "Reg Sense: 'mechanical fall' is written neatly, but the patient cannot explain why they were on the floor.",
    sender: "Your reg sense",
    source: "reg_sense",
    claimedUrgency: "unease",
    trueUrgency: "medium",
    category: "ambiguous",
    encounterId: null,
    timeToDeterioration: 90,
    vague: true,
    regSense: true,
    weight: 6,
    phases: ["early", "pre_handover"],
    ignored: {
      patientSafety: -8,
      reputation: -2,
      dangerousDelays: 1,
      datix: 0,
      handoverQuality: -2,
    },
    handledWell: {
      score: 50,
      clinicalConfidence: 3,
      patientSafety: 3,
      handoverQuality: 2,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login", "bed_manager"],
    delegationDuration: {},
  },
  {
    id: "new_af_ignored_by_problem_list",
    locationId: "cardiology",
    message:
      "Reg Sense: AF is on the monitor, but the problem list still says 'known sinus tachycardia'.",
    sender: "Your reg sense",
    source: "reg_sense",
    claimedUrgency: "soft signal",
    trueUrgency: "medium",
    category: "ambiguous",
    encounterId: null,
    timeToDeterioration: 75,
    vague: true,
    regSense: true,
    weight: 7,
    phases: ["deep", "pre_handover"],
    ignored: {
      patientSafety: -8,
      reputation: -2,
      dangerousDelays: 1,
      datix: 0,
      handoverQuality: -2,
    },
    handledWell: {
      score: 50,
      clinicalConfidence: 3,
      patientSafety: 3,
      handoverQuality: 2,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login", "bed_manager"],
    delegationDuration: {},
  },
  {
    id: "pre_handover_ward_too_quiet",
    locationId: "mau",
    message:
      "Reg Sense: the ward has gone suspiciously quiet just before handover, except for one bed space everyone avoids mentioning.",
    sender: "Your reg sense",
    source: "reg_sense",
    claimedUrgency: "vague",
    trueUrgency: "medium",
    category: "ambiguous",
    encounterId: null,
    timeToDeterioration: 85,
    vague: true,
    regSense: true,
    weight: 5,
    phases: ["pre_handover"],
    ignored: {
      patientSafety: -8,
      reputation: -2,
      dangerousDelays: 1,
      datix: 0,
      handoverQuality: -2,
    },
    handledWell: {
      score: 50,
      clinicalConfidence: 3,
      patientSafety: 3,
      handoverQuality: 2,
    },
    delegableTo: [],
    riskyDelegateTo: ["fy1", "trusted_fy2", "locum_no_login", "bed_manager"],
    delegationDuration: {},
  },
];

export const regSensePackTasks: TaskTemplate[] = rawRegSensePack.map(
  ({ encounterId, ...task }) => (encounterId ? { ...task, encounterId } : task),
);
